Add cryptography outline
boltlabs-inc/key-mgmt pull request #114
Opened 2022-08-04 14:54 UTC by marsella

Addresses #105 

This outlines the cryptographic types used in the flows in the arbitrary secrets proof of concept.

I'd like two kinds of reviews
- developer review: Read the docs and see if they make sense to you (e.g. as a user of the module). In particular, there are lots of key types introduced here and I want it to be clear what each one is used for. Check the signatures to see if there's any sketchy Rust stuff. Confirm that my minor rearranging of where types live makes sense to you (e.g. `Secret` moved).
- cryptographer review: Compare to the spec for completeness - did I get all the relevant types? Note that the actual encrypted types are not here yet; see #113. Compare docs to the spec for correctness. Check for general sketchy cryptography.

2022-08-04 14:57 UTC, marsella commented on dams/src/crypto.rs
> +    Default,
question for developers: Is this weird? I just use it to make a default `Secret` more easily, but it shouldn't be used in practice. I think I will want to take it out once this stuff starts getting implemented because a `Default` context doesn't mean anything in an actual / meaningful test.

2022-08-04 15:56 UTC, picklenerd commented on dams/src/crypto.rs
> +    Default,
I don't think it's weird in general. I really like this pattern for adding testing functionality.

In this case, I think it might be better to just pick a default value unless there's testing code that depends on it being set to `Default`.

2022-08-04 16:04 UTC, vidyaap reviewed
Thanks for outlining this! The changes and key types mostly make sense to me, but I had 2 questions:
- At what point are we encrypting the storage key with the master key and the master key with the export key?
- Where do the master and export keys live, and who ultimately uses them?

Also wanted to address the `Bytes` vs `BytesMut` question from earlier: I chose BytesMut before because Bytes doesn't have a `with_capacity()` function. If you don't need that anymore then switching to `Bytes` works!

2022-08-04 18:39 UTC, marsella commented on dams/src/crypto.rs
> +    Default,
As I typed out a response, I realized that I only use this to make a `Secret`, who (for now) will always use `Context::Secret`, and both of those parameters are easy to make a default version for. So I will replace with that and remove this variant.

2022-08-04 19:01 UTC, marsella commented
Here is the chain of key derivations / encryptions in registration (where all of these things are created / derived for the first time):
1. We get an `ExportKey` from OPAQUE and derive a `MasterKey` from it.
2. We generate a random `StorageKey`. This is the used to encrypt all of user's secrets that are stored by the servers.
3. We store the `StorageKey` at the server, encrypted with the `MasterKey`. 

>  At what point are we encrypting the storage key with the master key and the master key with the export key?

First, we don't encrypt the master key with the export key; we _derive_ the master key _from_ the export key. This happens every time the client authenticates with the server and plans to do an operation that involves secrets (generate-and-store, retrieve, probably import & export. Not auditing).

The client encrypts the `StorageKey` with the `MasterKey` at registration and sends the encrypted key to store at the server. They'll decrypt it every time they want to store or retrieve a `Secret` at the server.

Let me also answer two other questions that you didn't ask:
- Why do we derive a `MasterKey` instead of just using the `ExportKey`? We don't want to use the `ExportKey` directly as an encryption key because (a) it might not be the right format by default and (b) we might want to use it for multiple purposes. In (b), it's sketchy to use the exact same key for different purposes or schemes -- the composition of two secure schemes might produce an insecure one.
- Why don't we just use the `MasterKey` to encrypt all the user secrets (and skip the `StorageKey` entirely)? The `MasterKey` is derived from the user password; if the password changes, the `MasterKey` will also change. This means if a user forgets or resets their password, the reset process will require us to go decrypt everything encrypted under the old `MasterKey` and re-encrypt it with the new one. The storage key gives us a layer of indirection, so we only have to decrypt/re-encrypt one thing (the storage key) instead of many things (every secret the user is storing).

> Where do the master and export keys live, and who ultimately uses them?

They don't live anywhere! They are derived by the client after they authenticate with the server. The client uses them to access the storage key (which they will then use to encrypt and decrypt secrets). If the server ever learns these keys, our encrypted storage is broken. 

---
These are good questions and I think I should update the documentation to be more explicit about ownership (which party is allowed to know which key) and ephemerality (which keys are derived each time they are used and which are created once and need to be stored afterwards).

2022-08-04 20:59 UTC, vidyaap commented
> Here is the chain of key derivations / encryptions in registration (where all of these things are created / derived for the first time):

Thank you for this explanation, I think this is a lot clearer to me!  I can’t say I understand why we would only need to decrypt/re-encrypt the storage key with this setup but I also don’t think I need to know that for implementation. I can’t think of anything else off the top of my head that I’d need to know!

2022-08-04 21:01 UTC, marsella commented on dams/src/crypto.rs
> +use crate::{keys::KeyId, user::UserId};
Good call. I had debated leaving it in `keys` because is one of the only types that is used both in this version and in the expected end product, and I'm not sure if we should try to document / address that duality (since the final version is for keys, but this version is for `Secret`s). But I think pretending it's the final version one when we're using it here is not reasonable.

2022-08-05 13:19 UTC, vidyaap reviewed
Thanks for the doc and module changes! This looks good to me; just had one last question about the bytes type.

2022-08-05 16:36 UTC, vidyaap approved these changes

2022-08-06 01:09 UTC, marsella commented on dams/src/crypto.rs
> +    StorageKey,
@indomitableSwan  Should the context for a master key and storage key include user id or is it fine to leave as a static string?

2022-08-08 16:04 UTC, indomitableSwan requested changes
This looks pretty good to me, but:
- Please add high level documentation for the `crypto` module on the dams crate page. Right now this documentation is very sparse when it comes to module descriptions.
- I'm a little leery that every type of key seems to be public. Am I misunderstanding this? There are key types that should never exported or used outside of our code (`MasterKey`, `ExportKey`, `StorageKey`) and keys that should have to be explicitly exported in order to be accessed by other code (`Secret` types). Is making them all `pub` really the correct approach to prevent misuse by the calling application here?
- I advise reconsidering the `Context` abstraction. See individual comments related to this.

2022-08-08 18:43 UTC, marsella commented on dams/src/crypto.rs
> +impl Default for Secret {
I could pass an RNG and generate 32 random bytes, instead? I thought that having the default be totally nothing would be better than having it look like maybe it's a reasonable algorithm, though. I could also try moving this into the test module entirely. I plan to take this out as soon as we have a correct secret generation function, so I could also just replace calls to `Default` with calls to the original secret generation function.

2022-08-08 19:04 UTC, marsella commented on dams/src/crypto.rs
> +enum Context {
That's a reasonable concern. My train of thought was basically
- context requires correctly formatting some semi-static string in multiple places (e.g. encryption and decryption), so it should be defined as a type somewhere for easy replicability
- There are a bunch of contexts that might be slightly different, so we should put them all in one place so they're easier to distinguish via good documentation.

I am a bit confused about what you mean by parameters and primitives stored as part of the key itself. Do you mean that those things will be implied by the format of the key? That the key is a pair of `(secret bytes, parameters || primitives)`? If the latter, I did intend to keep those contexts as variants here as well. 

I'm open to exploring other options. We could have each context be its own type. I also considered having context be a static method on various types (e.g. `StorageKey::context()` returns the primitives and parameters) but this felt a bit messy because some contexts are attached to objects and others are attached to operations.

2022-08-09 13:30 UTC, indomitableSwan commented on dams/src/crypto.rs
> +enum Context {
> Re: staying close to where it is used. So far, all the context-requiring operations are in the same module. To me, making more types and positioning them at better lines in the file doesn't add any significant "closeness". But the static method on types approach would.

Yes, I was hinting at the latter approach, not moving around lines in the file.

2022-08-09 13:44 UTC, indomitableSwan commented on dams/src/crypto.rs
> +enum Context {
> That's a reasonable concern. My train of thought was basically
> 
> * context requires correctly formatting some semi-static string in multiple places (e.g. encryption and decryption), so it should be defined as a type somewhere for easy replicability
> * There are a bunch of contexts that might be slightly different, so we should put them all in one place so they're easier to distinguish via good documentation.
> 
> I am a bit confused about what you mean by parameters and primitives stored as part of the key itself. Do you mean that those things will be implied by the format of the key? That the key is a pair of `(secret bytes, parameters || primitives)`? If the latter, I did intend to keep those contexts as variants here as well.

I mean we should store information on the selected parameters and intended usage for the key as part of the key material itself, so the latter. It does not really make sense to me to use this abstraction for tracking arbitrary secret contexts as well; it seems as though we need a way for the caller to set context at key generation, in order to realize a flexible system for safe handling of arbitrary secrets.

> 
> I'm open to exploring other options. We could have each context be its own type. I also considered having context be a static method on various types (e.g. `StorageKey::context()` returns the primitives and parameters) but this felt a bit messy because some contexts are attached to objects and others are attached to operations.

The static method seems like a good option to me.

2022-08-09 13:50 UTC, indomitableSwan commented on dams/src/crypto.rs
> +enum Context {
> > That's a reasonable concern. My train of thought was basically
> > 
> > * context requires correctly formatting some semi-static string in multiple places (e.g. encryption and decryption), so it should be defined as a type somewhere for easy replicability
> > * There are a bunch of contexts that might be slightly different, so we should put them all in one place so they're easier to distinguish via good documentation.
> > 
> > I am a bit confused about what you mean by parameters and primitives stored as part of the key itself. Do you mean that those things will be implied by the format of the key? That the key is a pair of `(secret bytes, parameters || primitives)`? If the latter, I did intend to keep those contexts as variants here as well.
> 
> I mean we should store information on the selected parameters and intended usage for the key as part of the key material itself, so the latter. It does not really make sense to me to use this abstraction for tracking arbitrary secret contexts as well; it seems as though we need a way for the caller to set context at key generation, in order to realize a flexible system for safe handling of arbitrary secrets.
> 
> > I'm open to exploring other options. We could have each context be its own type. I also considered having context be a static method on various types (e.g. `StorageKey::context()` returns the primitives and parameters) but this felt a bit messy because some contexts are attached to objects and others are attached to operations.
> 
> The static method seems like a good option to me.

In terms of "messiness" --- that's an interesting choice of words. I think part of my uneasiness with the abstraction is that it seems like it's trying to do a lot of heavy lifting by  squashing different types of contexts into one place, rather than as part of the objects/operations for which the context is semantically meaningful.

2022-08-09 15:34 UTC, marsella commented on dams/src/keys.rs
> +
Yeah. This is the struct used in the "final version" import and export functions, so it won't affect this PoC. But I agree that it is not particularly great naming. Made #118.

2022-08-09 15:46 UTC, marsella commented on dams/src/crypto.rs
> +    pub fn encrypt_data(self, secret: &Secret) {
Decryption will be a function on the encrypted type, not on this. I will add in #113!

2022-08-09 15:48 UTC, marsella commented on dams/src/crypto.rs
> +    pub fn encrypt_storage_key(self, storage_key: StorageKey) {
Decryption will be a function on the encrypted type, not on this - see #113.

2022-08-09 16:11 UTC, marsella commented
> I'm a little leery that every type of key seems to be public. Am I misunderstanding this? There are key types that should never exported or used outside of our code (MasterKey, ExportKey, StorageKey) and keys that should have to be explicitly exported in order to be accessed by other code (Secret types). Is making them all pub really the correct approach to prevent misuse by the calling application here?

This project has a different crate structure than we've used in the past. These types are all defined in the `dams` crate, which holds all the types that are used by multiple endpoints (local client, remote client later, key server). The protocols themselves will be implemented in the endpoint crates: `dams-local-client` and `dams-key-server`. This `dams` crate should not be used directly by calling applications; they'll use the endpoint crates with our nice APIs. This structure means that we have to set all these types to be public, since they are used by external crates (`dams-local-client`), but they shouldn't be used outside our code.

I will add module-level documentation and be more explicit about the intended users of the crate & module.

2022-08-10 14:44 UTC, marsella commented
Okay, I added some wrappers around client-side functionality in order to try and reduce the volume of public fields and keys in the cryptography module. Based on how the spec is written, we can't make most of them completely private because we have operations like 
1. get key
2. send a message
3. use key

and this module doesn't handle any networking details. However, we can still restrict the functions available on the keys, so that the only thing you can do with a key once you get it is to use it in the intended way. I don't think we can prevent a rogue protocol developer from, say, exporting a key to the calling application (e.g. between 2 and 3), but this change should reduce the impulse because keys become less useful out of this specific context.

2022-08-10 14:48 UTC, marsella commented on dams/src/crypto.rs
> +pub struct ExportKey;
This is generated from external bytes and we'll need to pass the export key from the "open communiction session" networking functions out to the "run flow" protocol function, and then use it to encrypt / decrypt the storage key. I think the broadness of these steps will make it hard to have this be private. However, I made the `derive_master_key` function private.

2022-08-10 14:48 UTC, marsella commented on dams/src/crypto.rs
> +pub struct MasterKey;
Nope. This is now private.

2022-08-10 14:51 UTC, marsella commented on dams/src/crypto.rs
> +pub struct StorageKey;
Yes, the spec currently has a couple places where we retrieve (and decrypt) the storage key, then send a request to the server, then use the storage key. I assumed that we don't want to change that ordering (e.g. to retrieve the encrypted storage key, send a request, then decrypt and use it).

Since we're no going to put networking in this module, the dams client crates will need to see this type. However, I made the child functions (generate and encrypt data) private.

2022-08-10 14:52 UTC, marsella commented on dams/src/crypto.rs
> +pub struct Secret {
Doesn't it have to be public? What would the point of encrypted storage be without the ability to export a `Secret` after you retrieve it?

2022-08-10 14:56 UTC, marsella commented on dams/src/crypto.rs
> +impl Default for Secret {
I switched to the last option, so this no longer exists.

2022-08-10 15:00 UTC, marsella commented on dams/src/crypto.rs
> +    pub fn generate(
> we will want to include the selected AEAD scheme and chosen parameters.

This will be fixed for all secrets we create, so we don't need to pass it as a parameter. This function doesn't know the user and key ids, which is why we need to pass those, but it doesn't restrict the context to _only_ encode those two values.

2022-08-10 15:44 UTC, marsella commented on dams/src/crypto.rs
> +enum Context {
Okay, I removed the `Context` enum and will plan to add individual contexts as I go implementing specific type generations and operations..

2022-08-10 19:15 UTC, indomitableSwan commented on dams/src/crypto.rs
> +enum Context {
I am confused why contexts are no longer addressed in this PR.

2022-08-10 19:21 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    StorageKey,
On further reflection, what is our plan for versioning? We probably do want more informative context for  `export_key`, `master_key`, and `storage_key`, don't we?

2022-08-11 02:19 UTC, marsella commented on dams/src/crypto.rs
> +enum Context {
I was trying to make this PR include the main types and public APIs that will be used in the remaining flows. Based on your feedback, I concluded that context is not going to be a parameterized option for any of the APIs here, so I removed it. You did mention the possibility of user-provided context, but we haven't spec'd that out or generated concrete examples of where that should happen, and I don't want to try to do that on the fly here.

At this point, it seems to me like context is an implementation detail -- some combination of existing parameters (user id, key id), fixed parameters and schemes (the aead scheme, the current key-mgmt version), and static context strings ("lock keeper storage key" or whatever examples are in the spec). So I removed it from this PR, and we'll fill it in more carefully for each setting where it's used as we implement them.

2022-08-11 14:01 UTC, indomitableSwan approved these changes

2022-08-11 16:33 UTC, marsella commented on dams/src/crypto.rs
> +    StorageKey,
Yeah, I think `key-mgmt` version should be part of the context as well. I will link back to this comment when I make the implementation issues.

2022-08-11 16:35 UTC, marsella commented on dams/src/crypto.rs
> +pub struct Secret {
We discussed wrapper types for export, which I think makes sense. I'll make this `pub(crate)` and we can make a wrapper type or change the publicity when we get to the demo.

2022-08-11 16:36 UTC, marsella commented on dams/src/crypto.rs
> +    /// Arbitrarily generated Lock Keeper storage key.
Deleted this whole thing so no longer an issue :)

2022-08-11 18:03 UTC, merged