Tonic registration
boltlabs-inc/key-mgmt pull request #135
Opened 2022-08-12 17:44 UTC by vidyaap

2022-08-15 11:31 UTC, indomitableSwan commented
> 
> Questions:
> 

> * Should I remove the client's create- and retrieve-related code too, or save that for whoever makes the demo repo to take code from?

This is a question for @gijsvl.

2022-08-15 15:18 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
```suggestion
                    .map_err(|e| Status::aborted(e.to_string()));
```

It looks like this is just an error generated by the channel so I think it's safe to print it here.

2022-08-15 15:19 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
```suggestion
                    .map_err(|e| Status::aborted(e.to_string()));
```

2022-08-15 15:21 UTC, picklenerd commented on dams-local-client/src/api.rs
> +            .expect("Handle weird error type");
```suggestion
            .map_err(|e| Status::aborted(e.to_string()))?;
```

`expect` will panic if there's an error here.

2022-08-15 15:21 UTC, picklenerd commented on dams-local-client/src/api.rs
> +            .expect("Handle weird error type");
```suggestion
            .map_err(|e| Status::aborted(e.to_string()))?;
```

2022-08-15 15:22 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
```suggestion
                    .map_err(|e| Status::aborted(e.to_string()));
```

2022-08-15 15:22 UTC, picklenerd commented on dams-local-client/src/api.rs
> +            .expect("Handle weird error type");
```suggestion
            .map_err(|e| Status::aborted(e.to_string()))?;
```

2022-08-15 15:24 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
Resolving this one to comment on a bigger block

2022-08-15 15:25 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
```suggestion
                tx
                    .send(response.result)
                    .await
                    .map_err(|e| Status::aborted(e.to_string()))?;
```

We can get rid of the `let _ = ...` at the beginning if we add `?` to the end.

2022-08-15 15:30 UTC, picklenerd commented on dams-key-server/src/server.rs
> +        let service = config.services.get(0).unwrap();
I think this should return a `Result`. In general, it's ok to panic here since this only runs on startup but I think the panic should be triggered by the caller in `server.rs`.

2022-08-15 15:33 UTC, picklenerd commented on dams-key-server/src/command.rs
> +fn user_id_from_message(message: &[u8]) -> Result<UserId, Status> {
```suggestion
pub(crate) fn user_id_from_message(message: &[u8]) -> Result<UserId, Status> {
```

Nitpick: Rust allows this but it looks a little confusing as a reader.

2022-08-15 15:44 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +        let (tx, rx) = mpsc::channel(2);
Maybe we could define this `2` somewhere as a constant. If we think this value is going to be `2` for all of the protocols, it could just be a single constant either in the parent module or some generic `constants.rs` module. If we think it might be different for each protocol, it could just go at the top of files in each command submodule.

I think it would be good to have these constants somewhere obvious in case we run into problems with the channel size in the future. In theory, these channels should only ever have one message on them at at time so `2` gives us some leeway, but I wouldn't be surprised if this causes some weird bug in the future.

2022-08-15 19:31 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +                    .map_err(|_| Status::aborted("Handle weird error type"));
Ah thank you for pointing these out; I forgot to change them after copy-pasting!

2022-08-16 16:07 UTC, marsella requested changes
Thank you for this PR! The broad strokes look good to me. A lot of my comments are minor nits, code clarity stuff, etc. I see what you mean about tonic introducing a lot of boilerplate code and helper functions...

Re: deleting create and retrieve code. I think if you remove exactly that code in one commit and tag it with both this issue number and maybe #80, @gijsvl will be able to find it easily to re-add it.

Error handling: Please go through the PR to remove any places that ignore a result with `let _`. I marked a couple spots where you map an error (so it's clearly meaningful) but don't pass it up to the calling function with `?`. This can lead to difficult debugging if we're getting errors but silently ignoring them.

Some additional questions:
- Can you remove the transport crate as a dependency now (from server and tests)? I thought that just held the dialectic server (although it may have some helper functions I'm forgetting).

- My understanding of the `Arc<Mutex<StdRng>>` is that it's a shared, mutable reference, right? So many threads might have access, but only one can use at a time and they'll all get the update on use so we'll avoid repeated random values?

- Can you add the `protoc` requirement to the README? Or make an issue to do it.

Edit: 
- You mentioned the local client API generating a lot of helper functions. Maybe that is another spot for a little private submodule, to move them to a separate file and have some generated documentation? From looking through those helpers, I don't see an obvious way to simplify / unify them into fewer functions or a macro.

2022-08-16 18:23 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
This was a `let _` because the result is a result of an option and both the result and the option are ignored here. Is it better to do the `map_err` and then an `ok_or_else` or just leave it this way?

2022-08-16 18:24 UTC, vidyaap commented on dams-key-server/src/server.rs
> +            service: service.clone(),
The config is borrowed when you do `.get()` on it and the service you get from `.get` is a reference so I cloned it to get the actual object. Is there a better way to handle that?

2022-08-16 18:24 UTC, vidyaap commented on dams-key-server/src/server.rs
> +            .run(request, &self.db, self.rng.clone(), &self.service)
Yep, this doesn't clone the RNG itself.

2022-08-16 18:25 UTC, vidyaap commented on dams-local-client/src/api.rs
> +                // TODO: unwrap bytes from result and put here?
Sorry this was another thing I forgot to delete. It's not relevant anymore.

2022-08-16 18:34 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +     */
I wasn't sure what to do with the server helpers because the ones I left in their respective files are specific for the types for that command (e.g. the ones in the register file only deal with the types for `Register`). Would it still be best to move these helpers elsewhere?

But yes in terms of docs, wherever we end up putting these functions, I can replace their docs with ones that will build.

2022-08-16 18:51 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +        let _ = tokio::spawn(async move {
I considered this too but it does seem to work in in the tests. Basically, this handler function needs to return in order to send the channel back to the client. The task that spawns should continue running after this function returns. I don't think the task will cancel when it goes out of scope but there's no way to track it that I can think of.

Any errors that happen in this thread will get passed through the channel so I'm not worried about losing errors, but I'm still a little concerned about the lifetime of this thread. I don't think we should explore it in this PR but it's worth opening an issue to figure out what's happening here.

2022-08-16 18:52 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +     */
These are going to go away in #152 so I think it's ok to leave this for now.

2022-08-16 18:53 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +            None => Err(Status::invalid_argument("No message received")),
This will be covered by #152.

2022-08-16 18:56 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
I think you should definitely add the `?` to the existing `map_err`.

Is it an error if the option is `None`? If if is then we should add `ok_or_else(...)?`. If it's not then I think `let _` is the only option.

2022-08-16 18:58 UTC, picklenerd commented on dams-key-server/src/server.rs
> +            service: service.clone(),
I don't think there's a way without storing a `&Config` but that would be a nightmare. I don't think cloning during startup is a big deal.

2022-08-16 18:59 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
Hmm I guess it would be an error if the create function didn't also return the ID of the new user so I'll go with the `ok_or_else`.

2022-08-16 19:47 UTC, vidyaap commented on dams-local-client/src/api.rs
> +            Self::client_register_start(client_registration_start_message, user_id);
@picklenerd is it fair to say that this will also be covered by #152?

2022-08-16 19:51 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
Actually it still claims that this is an unused result after adding the `ok_or_else`.

2022-08-16 20:07 UTC, picklenerd commented on dams-local-client/src/api.rs
> +            Self::client_register_start(client_registration_start_message, user_id);
Yep! Everything involving helper functions will be covered by #152.

2022-08-16 20:19 UTC, marsella commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
Do you need two `??`s? One for the outer `Result`, one for the inner `Option` that gets turned into a `Result` with `ok_or_else`?

2022-08-16 20:19 UTC, marsella commented on dams-key-server/src/server.rs
> +            service: service.clone(),
I see, thanks.

2022-08-16 20:21 UTC, marsella commented on dams-local-client/src/api.rs
> +            Self::client_register_start(client_registration_start_message, user_id);
Oh, that's lovely. Thank you! And sorry to have left so many comments about things you already thought about!

2022-08-16 20:25 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
I tried `.map_err()?. ok_or_else()?` which gave the unused warning and `.map_err()?. ok_or_else()??` which was not allowed because it's already an `ObjectId` type after the first `?`.

2022-08-17 20:52 UTC, vidyaap commented
Addressing 2 of the comments from @marsella's original comment that didn't get their own conversation:

- Re: client CLI - I went ahead and deleted those files in one commit and marked them with both #98 and  #80 like you said.
- Re: transport dependency - yes I can, but I held off to ask: can we also remove the protocol.rs and transport.rs files from `dams`? The protocol.rs one seems like a yes but it looks like there are some useful types in transport.rs. I ask because if I can delete both, then I can also remove transport and dialectic as dependencies in `dams` as well as the server and tests.

2022-08-17 20:54 UTC, vidyaap commented on dams-key-server/src/command/authenticate.rs
> +        let (tx, rx) = mpsc::channel(2);
I might move them to the top of files for now. Not sure if #152 will affect this, but it might give us a better idea of where to put constants and also if there are additional constants that come out of that.

There are also some other constants like database table names that I'd like to put somewhere; not sure if they can all go in the same place or if we need a couple of constants files?

2022-08-17 22:11 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +        let (tx, rx) = mpsc::channel(2);
Top of the file sounds good for now. Things like table names will probably end up in a config at some point so it might be nice to have them in a single constants file so we don't need to round them up later.

2022-08-18 13:52 UTC, vidyaap commented on dams-key-server/src/command/authenticate.rs
> +        let (tx, rx) = mpsc::channel(2);
I moved the buffer size and table names to a constants file but I wasn't sure about visibility? They'd have to be changed to be public to use them in the tests - is that okay to do?

2022-08-18 13:56 UTC, marsella commented on dams-key-server/src/command/register.rs
> +        let _ = tokio::spawn(async move {
Okay, I still am not sure I understand the mechanics of how an error here gets back to the channel without the handle, but as long as the "register a user twice" test fails properly, I'll let it go.

2022-08-18 14:19 UTC, marsella commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
Okay, I see what you mean. I think this a bit of a misleading error message. With the two question marks and no `let _`, I get the error

```
warning: unused result of type `mongodb::bson::oid::ObjectId`
   --> dams-key-server/src/command/register.rs:155:9
    |
155 | /         User::create_user(db, &uid, server_registration)
156 | |             .await
157 | |             .map_err(|_| Status::aborted("Unable to create user"))?
158 | |             .ok_or_else(|| Status::aborted("Created user but with invalid ID??"))?;
    | |___________________________________________________________________________________^
    |
note: the lint level is defined here
   --> dams-key-server/src/lib.rs:3:9
    |
3   | #![warn(unused_results)]
    |         ^^^^^^^^^^^^^^
```
Rust docs have two levels of warning for unused results. 
1. `unused_must_use`: Warn about types and functions that are labelled "must-use". This is on by default. [Capital-R `Results` are must-use](https://github.com/rust-lang/rust/blob/1.5.0/src/libcore/result.rs#L241-L255), so if you ever get one back from a function, you have to do something with it.
2. `unused_results`: [Warn about any value returned by a function that is ignored](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/unused/static.UNUSED_RESULTS.html). This is not on by default, but we've turned it on here. The "results" here are lowercase-r results, AKA any type that comes back from a function. As the docs say, this can be noisy.

Our goal here is to raise errors if `create_user` returns an error (the outer result is `Err`) or if it fails to create a valid object id (the inner option is `None`). So, I think we should have two question marks, to catch the two errors, and a `let _` to ignore the option id that we don't need here (and silence the `unused_results` warning). 

```rust
    let _object_id = User::create_user(db, &uid, server_registration)
        .await
        .map_err(|_| Status::aborted("Unable to create user"))?
        .ok_or_else(|| Status::aborted("Created user but with invalid ID??"))?;
```

Some other refactoring options (probably for later) are
- Remove the inner `Option` inside the create user function, because it seems like a problem to insert a new thing into our database and have its ID be unparseable immediately. Here, it would remove the `ok_or_else` but keep the `let _object_id`. 
- Rewrite the `create_user` function to return `Result<(), Err>` instead of the object ID. Add the object ID back in if we ever find a scenario where we need it.

If we do both of these, this line would become the relatively sleeker
```rust
    User::create_user(db, &uid, server_registration)
        .await
        .map_err(|_| Status::aborted("Unable to create user"))?;
```

2022-08-18 14:24 UTC, picklenerd commented on dams-key-server/src/command/authenticate.rs
> +        let (tx, rx) = mpsc::channel(2);
I think it's ok for this PR.

2022-08-18 14:35 UTC, vidyaap commented on dams-key-server/src/command/register.rs
> +            .map_err(|_| Status::aborted("Unable to create user"));
Ah okay, thanks for the explanation! I wasn't a big fan of the `Result<Option>` construction in the original [mongo PR](https://github.com/boltlabs-inc/key-mgmt/pull/95#issuecomment-1192830532) so I'm happy to refactor this later.

For now, I'll change it to what's in your comment.

2022-08-18 14:58 UTC, marsella reviewed
> * Re: client CLI - I went ahead and deleted those files [...]

Thank you! 

> * Re: transport dependency - yes I can, but I held off to ask: can we also remove the protocol.rs and transport.rs files from `dams`? The protocol.rs one seems like a yes but it looks like there are some useful types in transport.rs. I ask because if I can delete both, then I can also remove transport and dialectic as dependencies in `dams` as well as the server and tests.

Yes, I think you can remove both of those. The extra stuff in transport.rs is error parsing for our custom URL format (`keymgmt://[key server address]`). Maybe we'll want to add this back in later because it's cute and I think makes it marginally harder to spam our server, but for now I think it's fine to remove. We can reference the [equivalent version in zeekoe](https://github.com/boltlabs-inc/zeekoe/blob/main/src/transport.rs) or come find your deletion commit if we want to build it back in.

2022-08-18 15:37 UTC, vidyaap commented
> Yes, I think you can remove both of those. The extra stuff in transport.rs is error parsing for our custom URL format (`keymgmt://[key server address]`) ...

I removed dialectic and transport, but I wanted to confirm a couple of resulting changes too:
- The `backoff` field of the client config had to be removed.
- The `server` field of the `SessionConfig` also had to be removed. 

I think the `server` field change is fine since the tonic client object has the information for how to connect to the server, but I wanted to make sure that both these changes are okay/make sense.

2022-08-18 16:01 UTC, marsella approved these changes
The `backoff` field is part of the retry strategy for connecting to the server. I'm guessing with the tonic server, we now have a "try once, then give up" strategy. I think this is fine for now, but as we scale and continue development work, we should implement a better strategy for retrying, reconnecting, and generally handling network failures.

I agree with you about the `server` change. Once the dust has settled a bit, we may revisit the distinction between a `Session` and a `DamsLocalClient` and decide if it makes sense to unify them or change the abstraction somehow. This seems like a good starting place, though.

2022-08-18 16:30 UTC, merged