Add encryption abstraction
boltlabs-inc/key-mgmt pull request #151
Opened 2022-08-15 16:58 UTC by marsella

Closes #113.

This adds some more (mostly private) infrastructure for implementing encryption. I've started to add some implementation-detail scaffolding to make sure I understand my type signatures correctly (e.g. `AssociatedData`). I updated all the function signatures that are supposed to take

I've decided to punt all the `!Send` security-based decision making to #108. 

I have a few dev questions inline. Would also like a cryptography review from @indomitableSwan.

2022-08-15 17:04 UTC, marsella commented on dams/src/crypto.rs
> +    pub fn decrypt_secret(self, _storage_key: StorageKey) -> Secret {
Dev question: compare this to the `decrypt_storage_key` function in `client.rs` (you probably can't see it in this PR). Is one of these better? This is a struct method, the other one is just a floating function. Now that I've written this one out, I slightly prefer it, if only because for the other functions I've been trying to write chain-able methods.

E.g. we can already do 
```rust
opaque_export_key
    .derive_master_key()
    .encrypt_storage_key()
```
and it might be nice to maintain that style rather than calling a separate function.
```rust
let encrypted_storage_key = opaque_export_key
    .derive_master_key()
    .encrypt_storage_key();

decrypt_storage_key(export_key, encrypted_storage_key);
```
These things won't be called in line like this outside of tests, though.

2022-08-15 17:10 UTC, marsella commented on dams/src/crypto.rs
> +    Bytes: From<T>,
Dev question: These trait bounds might change depending on which encryption scheme we use and what kind of representation they require, so I put them in the impl block instead of at the struct definition. Is that reasonable? Orphan rules would prevent someone outside this crate from doing a separate `impl` block with different/no bounds on `T`, right?

Alternately, is it a better option to require `Serialize` and `Deserialize` here, derive them automatically on all the relevant types, and then do the conversion between the serde output and the AEAD input type within this implementation? My goal is to reduce errors due to inconsistent conversions around encryption and decryption.

2022-08-15 17:17 UTC, marsella commented on dams/src/crypto.rs
> +struct AssociatedData(String);
FYI: I plan to add some methods to expand an existing associated data with additional information. E.g. you can append a string or maybe we can have fixed functions that define certain parameter choices that are used in multiple places in the code.
```rust
let context: AssociatedData = AssociatedData::default()
    .with_aead_parameters()
    .with_string("Lock Keeper storage key. ");
println!("{}", context);
```
would give

> Version 0.1: Arbitrary secrets proof of concept. AEAD parameters: (whatever) scheme with (something) key size. Lock Keeper storage key.

2022-08-15 17:19 UTC, marsella commented on dams/src/crypto.rs
> +pub struct Secret {
I had to change the publicity on this to allow us to return an `Encrypted<Secret>` for use elsewhere. I think this is fine because there are no public functions to generate arbitrary secrets.

2022-08-15 18:20 UTC, picklenerd commented on dams/src/crypto.rs
> +    Bytes: From<T>,
Yeah putting the bounds in the `impl` block is reasonable. This is the recommended pattern for generic bounds in general unless you have a really good reason to put them in the `struct` definition.

Orphan rules wouldn't prevent someone from implementing this with different bounds (or no bounds) in another crate but it looks like they'd have no way to construct an `Encrypted` since it's all private fields, so I think it's still safe.

It's probably worth adding a note to the struct's doc comments that no one should be attempting to `impl` this outside of this crate just to make it clear.

2022-08-15 18:23 UTC, picklenerd commented on dams/src/crypto.rs
> +    pub fn decrypt_secret(self, _storage_key: StorageKey) -> Secret {
I like this better too. I think it's a good generalization and it centralizes encryption/decryption functionality a bit more.

2022-08-16 12:54 UTC, indomitableSwan requested changes
Looks pretty good. There are a couple questions/comments inline, with a few nits that I'd like fixed.

Also: L136 in crypto.rs has a typo.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    #[error("Failed to decrypt ciphertext and/or authenticate associated data")]
Nit: Given how AEADs work, I would just say "AEAD decryption failed" here, or if you are hiding that we are using an AEAD, just "decryption failed".

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +/// The associated data and additional context used in [`Encrypted`] AEAD
Nit: Technically everything is associated data for the AEAD here, so I would delete "and additional context".

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +struct AssociatedData(String);
This looks good.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +            "Version 0.1: Arbitrary secrets proof of concept. ",
Nit: I might be tempted to just use, e.g., alphanumeric naming or numbering without additional context for versioning.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +/// A ciphertext representing an object of type `T`, encrypted under (TODO #107:
Add "an AEAD" before the TODO note.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +/// authentication blob separate from the ciphertext), or the types might
What do you mean by "authentication blob" here?

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +/// A well-formed symmetric encryption key for the (TODO #107: specify
Add "an AEAD" before the TODO note here.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +struct AeadKey;
Nit: Consider using simpler naming here, like `SymKey` or `EncKey` (a little weird, admittedly).

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    Bytes: From<T>,
@picklenerd, can I poke you to expand on your above answer and comment on the serde alternative @marsella described?

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    /// associated data fails to authenticate.
Same nit as above - I don't think it's necessary to include all reasons _why_ decryption might fail, and typically you'd just talk about decryption failing here. (Which is to say, you don't _learn_ the reason that decryption failed here.)

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    pub fn decrypt_secret(self, _storage_key: StorageKey) -> Secret {
I like it better, too.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto.rs
> +pub struct Secret {
Maybe at some point (with more developers onboarded) we can re-evaluate our structuring for this project, but this seems OK.

2022-08-16 12:54 UTC, indomitableSwan commented on dams/src/crypto/client.rs
>  /// server. This key should be sent to the server for storage.
Technically, this is called _during_ an open registration session.

2022-08-16 13:43 UTC, picklenerd commented on dams/src/crypto.rs
> +    Bytes: From<T>,
On `serde`, I think I need to know more about how this will be implemented. If `serde` is how you're going to get from bytes to `T` then I think adding `Serialize` and `Deserialize` bounds will be required no matter what. It might be worth breaking this up into two `impl` blocks in that case so the bounds are more appropriate for each function. I might be misinterpreting this question though.

2022-08-16 13:57 UTC, picklenerd commented on dams/src/crypto.rs
> +    Bytes: From<T>,
To expand on my answer above:

I just double checked the orphan rule and it doesn't actually apply here since this isn't a trait `impl`. You would be blocked from writing an `impl` block here based on the normal rules for writing `impl` blocks for a `struct`.

The protection I mentioned above is just that `Encrypted` contains a bunch of private fields but no constructor. Since no one outside of this module can see the private fields, there's no way to construct an `Encrypted` from outside of this module. The only way to get one from outside would be to call `Encrypted::encrypt`.

2022-08-16 16:05 UTC, picklenerd commented on dams/src/crypto.rs
> +pub struct Secret {
Do you think we'll ever add more fields to this? Maybe this could be `struct Secret(Bytes)` to emphasize that it's a wrapper.

2022-08-16 18:04 UTC, marsella commented on dams/src/crypto.rs
> +            "Version 0.1: Arbitrary secrets proof of concept. ",
That's fair. We might want to come up with a versioning policy or something to determine what minor and major version bumps look like and keep a history of what changed at each version, but I'm happy to put that off at least until we change it for the first time.

2022-08-16 18:07 UTC, marsella commented on dams/src/crypto.rs
> +/// authentication blob separate from the ciphertext), or the types might
I wasn't sure if the AEAD scheme would keep the ciphertext bit separate from the authenticated bit. I'll edit this comment to remove the speculative parenthetical.

2022-08-16 18:13 UTC, marsella commented on dams/src/crypto.rs
> +struct AeadKey;
I switched it from `EncryptionKey` because it felt so vague! But I'll put it back :)

2022-08-16 18:26 UTC, marsella commented on dams/src/crypto.rs
> +    Bytes: From<T>,
Re: serde. The options I've considered are:

1. Require the to/from `Bytes`. Convert in the `encrypt` function from Bytes to whatever representation the AEAD scheme uses.
2. Require a to/from the specific representation the AEAD scheme uses (e.g. `Vec[u8]`).
3. Require `Serialize` and `Deserialize`. Convert in the `encrypt` function from whichever serde output we choose to the representation the AEAD scheme uses.

In hindsight, (2) is not a great option because switching schemes would maybe require changing the bounds to match the output of the new scheme (or adding a conversion step in `encrypt`). The benefit of (3) over (1) is serde's automatic derivation, which might help avoid programmer error.

2022-08-16 18:35 UTC, marsella commented on dams/src/crypto.rs
> +pub struct Secret {
Yes! It will also have `AssociatedData` -- now that you mention it, I'll just add that field from now.

2022-08-16 19:39 UTC, picklenerd approved these changes
This looks good to me from a code perspective.

2022-08-16 19:44 UTC, picklenerd commented on dams/src/crypto.rs
> +    Bytes: From<T>,
One nice thing about 1 is that you can do the `serde` stuff in the `From` impl but leave the option open for other types to do something other than `serde`.

2022-08-16 20:32 UTC, marsella commented on dams/src/crypto.rs
> +    pub fn decrypt_secret(self, _storage_key: StorageKey) -> Secret {
Fixed!

2022-08-16 20:33 UTC, marsella commented on dams/src/crypto.rs
> +    Bytes: From<T>,
That's a good point. I think I'll leave it as-is for now and see if we run into anything weird once we implement it.

2022-08-17 12:39 UTC, indomitableSwan approved these changes
I am OK with this PR now, but the encryption signature doesn't match what is in the spec currently. That is, the ordering of inputs is different.

Will this discrepancy cause implementation errors? If so, we should resolve the discrepancy, either here or in the spec.

2022-08-17 12:43 UTC, indomitableSwan commented on dams/src/crypto.rs
> +struct AeadKey;
Yes, these are all feeling a bit vague. I think my discomfort here is entirely aesthetic, ie., I don't like the way Rust naming conventions play with acronyms.

2022-08-17 12:48 UTC, indomitableSwan commented on dams/src/crypto.rs
> +/// authentication blob separate from the ciphertext), or the types might
Ahh. I just took a look at RustCrypto's trait, and it does look like they don't keep these separate.

2022-08-17 13:41 UTC, marsella commented
Good catch! I'll fix encryption to match. Note that the specific encryption calls (`encrypt_storage_key`, `encrypt_data`) already match the expected format of (key, value). 

Decryption doesn't match because of Rust formatting standards -- the spec says `Dec(key, ciphertext)` but we have decryption as a function on the ciphertext, so the arg order is `Dec(ciphertext, key)`. I don't think this will cause errors, though -- it feels obvious to me which argument is which :)

2022-08-17 13:58 UTC, merged