Use the HKDF library to create a master key
boltlabs-inc/key-mgmt pull request #169
Opened 2022-08-23 16:29 UTC by marsella

Closes #130

This PR uses the Rust-Crypto HKDF library to extract a master key from the export key. To support this, it
- expands the associated data type to support all the relevant context
- expands existing key types, filling in wrappers for export key and master key, adding context to encryption key

To do
- add tests
- make corresponding PR in spec to address boltlabs-inc/key-mgmt-spec#71

2022-08-24 13:59 UTC, picklenerd commented on dams/src/crypto.rs
> +            .map_err(CryptoError::KeyDerivationFailed)?;
Yeah I think it's good to handle it just in case and also good to indicate that it should never return an error. It's probably worth logging this as an error as well so we have a way to see if this is triggering an error when it's not supposed to.

2022-08-24 14:38 UTC, indomitableSwan requested changes
Looks just about there! A couple of documentation typos/nits, some recommendations for simplification, and a couple comments/questions on testing.

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +            .with_hkdf_parameters();
I would remove the `.with_hkdf_parameters()` context; it's not yet clear that we will need it. Maybe we should expand the issue description for https://github.com/boltlabs-inc/key-mgmt-spec/issues/57 so that we remember to revisit.

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        let hk = Hkdf::<Sha3_256>::new(None, &self.0);
Nit: I would prefer a comment here that documents usage of `Hkdf`, e.g., "Produce a uniformly distributed secret using an export key as input key material".

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        hk.expand((&associated_data).into(), &mut master_key_material)
Nit: I would prefer a comment here that documents usage of `Hkdf`.

Dependency comment: I do not like the API for this dependency very much. Quite goofy that they don't just provide a single function call for HKF that takes the input key material, optional salt, info string, output length and outputs your key.

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    // In practice, an export key will be a pseudorandom output form OPAQUE.
Typo: "form" --> "from"

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +    }
Does `pub(crate)` mean someone could call this function outside these unit tests?

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        assert!(master_key.0.key != export_key.0)
I guess other "not obviously broken" test might be to make sure it's not all zeroes, and that adding information using `expand` actually results in a different key.

2022-08-24 14:38 UTC, indomitableSwan commented on dams/src/crypto/client.rs
> +        let _ = create_and_encrypt_storage_key(&mut rng, export_key);
Ah. Is this why we set the visibility for `export_key` the way we did? Are there other ways we might structure testing to avoid future misuse? Or perhaps even renaming would help. I suppose if we end up with a low-level secret generation building block, we could also use that in testing when we need a key distributed uniformly at random for testing purposes.

2022-08-24 18:32 UTC, marsella commented on dams/src/crypto.rs
> +        hk.expand((&associated_data).into(), &mut master_key_material)
Yeah, it's a bit weird. The documentation specifically says
> you expand it (perhaps multiple times) into some Output Key Material (OKM) 

I found a deprecated version of RustCrypto that does have it as a single function, but I'm guessing they changed it to support the multiple-key use case. Anyway, I moved these two calls together so they're more obviously a single thing.

2022-08-24 18:34 UTC, marsella commented on dams/src/crypto.rs
> +    }
Yes, but it won't compile unless it's called from a test (since this whole module is `#[cfg(test)]`). I have this visibility so I can make a sample export key for testing in the `client` submodule.

2022-08-24 18:38 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        hk.expand((&associated_data).into(), &mut master_key_material)
Yeah, it's fine to _allow_ access to extract and expand functionality, but odd that they wouldn't just provide the most basic use case as one function call.

2022-08-24 18:50 UTC, marsella commented on dams/src/crypto.rs
> +        assert!(master_key.0.key != export_key.0)
Added these. I'm a little leery of the last one because it has a strong dependence on the implementation of the function -- if we use a different HKDF implementation, I'm not sure this will be a useful test (or we'll have to change it to also use the new HKDF). It doesn't test the API of the function, ya know? 

Anyway, this also inspired me to add another test that different export keys produce different master keys.

2022-08-24 18:59 UTC, marsella commented on dams/src/crypto/client.rs
> +        let _ = create_and_encrypt_storage_key(&mut rng, export_key);
Yep! I can rename right now. 

One option is for me to move the two functions in this submodule to be methods on the export key and storage key, respectively. Then all the tests would be in one module and `export_key` could be private. I have been thinking about doing this for a while, but waiting until I got to the actual implementation of these functions to do it.

2022-08-24 19:18 UTC, marsella commented on dams/src/crypto.rs
> +        self.with_str("HMAC-based extract-and-expand key derivation function using SHA3-256")
Removed!

2022-08-25 11:37 UTC, indomitableSwan commented on dams/src/crypto/client.rs
> +        let _ = create_and_encrypt_storage_key(&mut rng, export_key);
I like that option.

2022-08-25 11:46 UTC, indomitableSwan approved these changes
This looks good to me. Responded to a couple of comments, but nothing blocking.

2022-08-25 11:46 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        assert!(master_key.0.key != export_key.0)
Yeah, that's a good point, and possibly an argument for creating our own KDF abstraction (emphasis on KDF here, not HKDF) eventually. I think this test is fine as is for now, though.

2022-08-25 14:13 UTC, picklenerd approved these changes

2022-08-25 14:16 UTC, merged

2022-08-25 16:39 UTC, marsella commented on dams/src/crypto/client.rs
> +        let _ = create_and_encrypt_storage_key(&mut rng, export_key);
I got confused and did this on the wrong PR. See [941cf15](https://github.com/boltlabs-inc/key-mgmt/pull/173/commits/941cf156e77a8c3f9a5936cad1d4eefc93219b45) in PR #173.