Add storage key to database #124
boltlabs-inc/key-mgmt pull request #182
Opened 2022-08-25 23:49 UTC by picklenerd

Closes #124

2022-09-07 18:06 UTC, marsella requested changes
I appreciate your move toward reduced network traffic, but the message ordering is not correct here. The user ID that the client gets from the server needs to be sent over an authenticated channel, which can only happen _after_ the opaque protocol is complete. 

I know we don't have authenticated channels yet, but I think it's better to separate the messages from now and flag them in the docs with #186, [as in authentication](https://github.com/boltlabs-inc/key-mgmt/blob/develop/dams/src/types/authenticate.rs#L48-L51) so it doesn't slip under our radar later.

2022-09-07 18:06 UTC, marsella commented on dams-key-server/src/command/register.rs
> +        return Err(DamsServerError::InvalidUserId);
This error overlaps with `AccountAlreadyExists`. I might keep the `InvalidUserId` above but replace this one.

2022-09-07 19:11 UTC, picklenerd commented on dams-key-server/src/command/register.rs
> +        return Err(DamsServerError::InvalidUserId);
Agreed. I think `AccountAlreadyExists` gives too much info.

2022-09-07 19:15 UTC, picklenerd commented on dams/src/types/register.rs
> +        pub storage_key: Encrypted<StorageKey>,
If that's the case, maybe creating a storage key should be a separate operation since the client is going to have to call register, then authenticate, then create the key.

2022-09-07 19:20 UTC, picklenerd commented
> I appreciate your move toward reduced network traffic, but the message ordering is not correct here. The user ID that the client gets from the server needs to be sent over an authenticated channel, which can only happen after the opaque protocol is complete.

I wasn't trying to do anything about network traffic. I was looking at the wrong page of the spec based on the link in the ticket: https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/system-functionalities.md#register

I think this is the correct page: https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/systems-architecture.md#opening-and-using-a-registration-session

2022-09-09 16:39 UTC, marsella reviewed
The protocol looks good to me! I have a couple inline questions about error handling and expected behaviors.

I also can't quite tell how the server can recognize that they're dealing with the same client between registration+authentication and creating the storage key, and whether they persist the information (the session key) they'll need soon to authenticate messages in this flow. This might be something we can address in #186, but we should make sure it's documented there if we'll need changes to the server.

More on error handling: How to we want to handle cleaning the server state if there are errors in creating & storing the storage key? A user won't be able to "try again" by running the registration protocol because their account will already exist. I'm not sure if this needs to be addressed right now, but we should think about what server behavior we'd expect in the long run (deleting the whole record and starting over? Adding a conditional to circumvent the "register" part of registration if the account exists without a storage key?)

2022-09-09 16:39 UTC, marsella commented on dams-key-server/src/command/create_storage_key.rs
> +    set_storage_key(&context.db, &user_id, client_message.storage_key).await?;
What happens if this fails? Should we send back a `CreateStorageKeyResult { success: false }`?

2022-09-09 16:39 UTC, marsella commented on dams-key-server/src/command/create_storage_key.rs
> +    ) -> Result<Response<MessageStream>, DamsServerError> {
question: I can't quite tell what the overall failure behavior is here. Does the client get some kind of error message if the server generates a `DamsServerError` here, or will the connection just drop?

2022-09-09 16:39 UTC, marsella commented on dams-key-server/src/server.rs
> +    ) -> Result<Response<Self::AuthenticateStream>, Status> {
Should this create a `CreateStorageKeyStream`? I see they map to the same type.

2022-09-09 17:14 UTC, picklenerd commented on dams-key-server/src/server.rs
> +    ) -> Result<Response<Self::AuthenticateStream>, Status> {
Yes it should! These type aliases are required by the `tonic` interface. Maybe it would be better to make them all return `MessageStream` and just let those type aliases sit around doing nothing.

2022-09-09 17:23 UTC, picklenerd commented on dams-key-server/src/command/create_storage_key.rs
> +    ) -> Result<Response<MessageStream>, DamsServerError> {
Right now the client will get whatever error is returned wrapped in a `tonic::Status`. I think we'll need to flesh out how we want errors displayed to the client in the future but I think this is best for now.

2022-09-09 17:24 UTC, picklenerd commented on dams/src/types/create_storage_key.rs
> +    /// pass user ID and registration-start message from OPAQUE
Updated. I was going to write similar comments but I don't think they add anything.

2022-09-09 17:24 UTC, picklenerd commented on dams-key-server/src/command/create_storage_key.rs
> +    set_storage_key(&context.db, &user_id, client_message.storage_key).await?;
I updated the `set_storage_key` docs with descriptions of all of the possible errors.

2022-09-09 17:27 UTC, picklenerd commented on dams-key-server/src/command/create_storage_key.rs
> +    set_storage_key(&context.db, &user_id, client_message.storage_key).await?;
It's not possible to get a `success` false at this point. We could probably use a better type for this. Something I've seen in the past is a generic `Success(bool)` type. Or we could do a basic two-variant enum.

2022-09-09 17:45 UTC, picklenerd commented
> I also can't quite tell how the server can recognize that they're dealing with the same client between registration+authentication and creating the storage key, and whether they persist the information (the session key) they'll need soon to authenticate messages in this flow. This might be something we can address in https://github.com/boltlabs-inc/key-mgmt/issues/186, but we should make sure it's documented there if we'll need changes to the server.

I think we never settled on how to store the session key. I remember we talked about potentially using redis but we could also store them in the `DamsKeyServer` for now. It looks like session key handling is described in #186 but it seems like we could break this off into its own issue since #186 is also concerned with the MAC solution.

2022-09-09 17:47 UTC, picklenerd commented
> More on error handling: How to we want to handle cleaning the server state if there are errors in creating & storing the storage key? A user won't be able to "try again" by running the registration protocol because their account will already exist. I'm not sure if this needs to be addressed right now, but we should think about what server behavior we'd expect in the long run (deleting the whole record and starting over? Adding a conditional to circumvent the "register" part of registration if the account exists without a storage key?)

This is a really good point. I think it would be easier to just delete the whole database entry. I'll make a new issue to address this.

2022-09-09 18:10 UTC, marsella commented
> > I also can't quite tell how the server can recognize that they're dealing with the same client between registration+authentication and creating the storage key, and whether they persist the information (the session key) they'll need soon to authenticate messages in this flow. This might be something we can address in #186, but we should make sure it's documented there if we'll need changes to the server.
> 
> I think we never settled on how to store the session key. I remember we talked about potentially using redis but we could also store them in the `DamsKeyServer` for now. It looks like session key handling is described in #186 but it seems like we could break this off into its own issue since #186 is also concerned with the MAC solution.

Oh, right. Thanks. I think it would be good to make a separate issue (maybe an issue belonging to that epic) about this specifically.

2022-09-09 18:18 UTC, marsella commented on dams-key-server/src/command/create_storage_key.rs
> +    set_storage_key(&context.db, &user_id, client_message.storage_key).await?;
Ah, I see. As you say below, we might want to revisit how we expose errors to the client but this should be fine.

2022-09-09 18:19 UTC, marsella approved these changes

2022-09-09 18:21 UTC, merged

2022-09-09 18:29 UTC, picklenerd commented
Created #213 to handle session keys