Add generate cryptography
boltlabs-inc/key-mgmt pull request #207
Opened 2022-09-06 16:07 UTC by marsella

Closes #134, closes #107 (checks the last box!)

- Updates several type representations to be more compatible with how they need to operate
   - Storage key is now an encryption key, not a secret. This also required updating the to/from `Vec<u8>` on a storage key. For modularity, I also implemented the conversion for an encryption key.
   - Associated data is now a byte array, not a string
- Adds encryption and decryption of secrets under storage keys
- Adds generation of key IDs.

Specific feedback on tests is particularly welcome.

2022-09-06 19:00 UTC, picklenerd commented on dams/src/crypto.rs
> +        AssociatedData(self.0.into_iter().chain(ad.bytes().into_iter()).collect())
I dunno if this would actually be better but I think you could use the `write!` macro here.

https://doc.rust-lang.org/std/macro.write.html

2022-09-06 19:04 UTC, picklenerd commented on dams/src/crypto.rs
> +
Nice timing! I was just about to write this myself for registration.

2022-09-06 19:10 UTC, picklenerd commented on dams/src/crypto.rs
> +            .get(len + 1..)
This syntax is a little confusing. I think it would help to make something like `let offset = len + 1` and then do `.get(offset..)`.

2022-09-06 19:16 UTC, picklenerd commented on dams/src/crypto.rs
> +pub struct OpaqueExportKey(Box<[u8; 32]>);
Does this need to be in a `Box`? I tried removing it and the tests still passed.

2022-09-06 19:18 UTC, marsella commented on dams/src/crypto.rs
> +pub struct OpaqueExportKey(Box<[u8; 32]>);
Not necessarily. On a previous project, I used lots of unboxed, fixed-length arrays and we ended up with a stack overflow. I've been defaulting to `Box`es to avoid that happening unexpectedly.

2022-09-06 19:20 UTC, picklenerd commented on dams/src/crypto.rs
> +        // But the key IDs are still unique!
This is great 😄

2022-09-06 19:23 UTC, picklenerd commented on dams/src/crypto.rs
> +pub struct OpaqueExportKey(Box<[u8; 32]>);
That sounds like a good reason. I can see that potentially being a problem on the remote client.

2022-09-06 19:43 UTC, picklenerd commented on dams/src/user.rs
> +        f.write_str(&format!("{:?}", self.0))
```suggestion
        write!(f, "{:?}", self.0)
```

2022-09-06 19:47 UTC, picklenerd commented on dams/src/user.rs
> +        f.write_str(&format!("{:?}", self.0))
If you still want this to print as a string, you could use this:
https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy

It'll replace any invalid UTF-8 bytes with a specific symbol and print everything else correctly.

2022-09-06 20:22 UTC, indomitableSwan requested changes
Looks OK, modulo some minor comments. 
- The abstractions seem a bit heavy-handed to me, but they are probably fine. The only place I suggest we might want to simplify now is with respect to `StorageKey`: I don't see why we have`encrypt_data` as a helper function. Seems like extra code that isn't particularly helpful.
- There are some naming inconsistencies/weirdness we might want to consider updating, either here or in a cleanup issue:
  - For `EncryptionKey`, we might want to consider the same change we made for `Secret`, where we use `context` as the field name for the context instead of `associated_data`.
  - It's a bit odd that to encrypt a secret we use `encrypt_data`, but when we later decrypt it's `decrypt_secret`.
- It also looks like some changes that do not belong in this PR were made, specifically with respect to transactions.rs. These should be reverted and the file left unchanged.

2022-09-06 20:22 UTC, indomitableSwan commented on dams/src/crypto.rs
> +        // This should never produce a ConversoinError because the lengths are
typo in `ConversionError`

2022-09-06 20:22 UTC, indomitableSwan commented on dams/src/transaction.rs
> -
why are you changing anything in transactions.rs in this PR?

2022-09-06 20:30 UTC, marsella commented on dams/src/transaction.rs
> -
`KeyId` is no longer a unit struct, so we'd have to implement a default constructor for `KeyId` in order to create this default `TransactionApprovalRequest`. I don't think that would be a useful or safe thing to have around, and we're not using this default impl anywhere, so I decided to remove this rather than add an unsafe constructor for `KeyId`.

2022-09-06 21:30 UTC, marsella commented on dams/src/user.rs
> +        f.write_str(&format!("{:?}", self.0))
Ah, I just moved this around in the file. But since you mentioned it:

We only use this for the database lookup -- `find_user_by_id()` uses the `doc!` macro that seems to require a string as input. I'm not sure if the lossy version would be OK for that, or if this version even works if there's a non-UTF character in there. I was actually hoping to remove it in favor of the `IntoIterator` since that's all I need for making associated data, but I couldn't tell if the `doc` macro could take non-string parameters. Maybe @vidyaap knows?

2022-09-06 21:34 UTC, marsella commented on dams/src/crypto.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Hash)]
I'll change it here, I think that's a good call.

2022-09-06 21:37 UTC, marsella commented on dams/src/crypto.rs
> +            .with_str("client-generated");
No, it is not particularly useful. I will combine. But for the record, one of the associated datas is the context for the generated secret, and one is the associated data for the encryption. They're technically, I think, separate things in the spec, even though they have the same value.

2022-09-06 21:39 UTC, vidyaap commented on dams/src/user.rs
> +        f.write_str(&format!("{:?}", self.0))
For the `doc` macro, it needs to be either something that implements `Into<Bson>` and `Clone`, or a `str` or bytes. Not sure if that is helpful for this though.

2022-09-06 21:45 UTC, marsella commented on dams/src/crypto.rs
> +            .with_str("client-generated");
It does make the tests nicer so we can get the secret that was generated instead of losing it in the "generate-and-encrypt" functionality. I'm using cloned RNGs right now to get around that (e.g. generate the secret manually with an RNG using the same state), but that's kind of fragile anyway -- if we change around the order of things in the function, we have to change the tests.

2022-09-07 10:22 UTC, indomitableSwan commented on dams/src/crypto.rs
> +            .with_str("client-generated");
> No, it is not particularly useful. I will combine. But for the record, one of the associated datas is the context for the generated secret, and one is the associated data for the encryption. They're technically, I think, separate things in the spec, even though they have the same value.

I was just thinking about this and realized I forgot to write down a comment. (I probably shouldn't pause during reviews.) It's a problem that `create_and_encrypt` doesn't return the actual generated secret, because the secret is meant to be passed to local storage (which right now the PoC spec just leaves this as a stub that stores the secret in the clear).

I think it's an odd choice to not pass the secret's `context` in directly as the associated data for encryption. If we decided at some point to make them different (which we won't, because they are the same value in the spec as part of the design, I just didn't give them a new name because that is an implementation detail and the spec is not pseudocode), then we could adjust the code as needed. Is there a way that I can make this more explicit in the spec repo? If we _want_ the spec repo to be pseudocode and dictate things like "pass the secret's context field into the AEAD", then I really need more help writing. To date, I haven't been trying to design the implementation, just write down the protocol.

2022-09-07 10:25 UTC, indomitableSwan commented on dams/src/transaction.rs
> -
Ah I see. This makes sense. Thank you for explaining.

2022-09-07 13:23 UTC, picklenerd commented on dams/src/crypto.rs
> +        AssociatedData(self.0.into_iter().chain(ad.bytes().into_iter()).collect())
```suggestion
        AssociatedData(self.0.into_iter().chain(ad.bytes()).collect())
```
I think the `Bytes` type that `bytes()` returns is already an iterator.

2022-09-07 13:47 UTC, marsella commented on dams/src/user.rs
> +        f.write_str(&format!("{:?}", self.0))
Hmm, the `as_bytes` method isn't compiling and this isn't causing any errors right now, so I think I will leave it as-is for now, if that's okay with @picklenerd.

2022-09-07 13:54 UTC, marsella commented on dams/src/crypto.rs
> +        AssociatedData(self.0.into_iter().chain(ad.bytes().into_iter()).collect())
Good call. I actually switched this to call into the `with_bytes` method for consistency.

2022-09-07 13:55 UTC, marsella commented on dams/src/crypto.rs
> +            .get(len + 1..)
Fixed! Both here and in the other bytes-parsing functions.

2022-09-07 14:28 UTC, indomitableSwan commented on dams/src/crypto.rs
> +            .with_str("client-generated");
Ah yes. That does make sense! It's a bit hard to say whether it's premature optimization, because certainly careless changes here could result in problems, as you point out. However, I can think of a couple different ways we might want to handle arbitrary contexts for secrets (which we don't support at the moment), some of which might be sensitive values, so perhaps we should decide on that abstraction when we are adding that feature, rather than now. If we're thinking about it now, I would probably adjust the secret to have a `default` context and an `arbitrary` context, and then just use the `default` directly in encryption for the associated data.

I'll also observe that in the protocol here we do not send the associated data over to the server for storage, because the server already knows these values. That is perhaps easy to misunderstand, and now that you've mentioned the issue, I am not clear if our encryption abstraction lines up to this or not. I also think it doesn't matter here, i.e., we could change the spec without any problems. We would just have to be sure that the key server checks the received associated data for correctness before storage (or otherwise doesn't rely on the content of the data for determining association with `user_id` and `key_id` in its database).

2022-09-07 14:36 UTC, indomitableSwan approved these changes
I am satisfied with the changes, but have a couple more questions/suggestions, and if you are making more changes based on these, please flag me again for another pass.

2022-09-07 14:36 UTC, indomitableSwan commented on dams/src/crypto.rs
> -
Given that we have created `StorageKey` as a wrapper around `EncryptionKey`, perhaps we should provide basic `encrypt` and `decrypt` (non-public) inner methods that are just wrappers around our encryption abstraction? I'm not sure what the argument are for and against this.

2022-09-07 14:36 UTC, indomitableSwan commented on dams/src/crypto.rs
> -
Given that we have created `StorageKey` as a wrapper around `EncryptionKey`, perhaps we should provide basic `encrypt` and `decrypt` (non-public) inner methods that are just wrappers around our encryption abstraction? I'm not sure what the argument are for and against this.

2022-09-07 14:36 UTC, indomitableSwan commented on dams/src/crypto.rs
> +            secret.clone(),
why do we have to clone the secret? i.e., when we made our encryption abstraction, do we want to pass the secret in directly or a reference to the secret?

2022-09-07 15:37 UTC, marsella commented on dams/src/crypto.rs
> +            .with_str("client-generated");
I added boltlabs-inc/key-mgmt-spec#123 to address your second concern.

2022-09-07 15:48 UTC, marsella commented on dams/src/crypto.rs
> +            secret.clone(),
The `encrypt` function requires a secret passed by value. Made #209 to reduce this.

2022-09-07 16:07 UTC, marsella commented on dams/src/crypto.rs
> -
I agree, but I would rather do this once we are ready to abstract more things with the same `StorageKey`.

2022-09-07 16:52 UTC, merged