Local client
boltlabs-inc/key-mgmt pull request #21
Opened 2022-06-07 15:05 UTC by marsella

Adds a local client API. New modules include:
- `localclient`: currently contains the API, but will expand to hold all the logic for the local client, too (e.g. calling the key server API)
- `keys`: currently contains keys and use permissions/restrictions, plus some miscellaneous things around authentication
- `transaction`: home of the transaction approval request. I am considering building this out to include all the blockchain-related functionality we'll need, like a crypto -> allowable schemes map and any validation code we want to run on transactions (e.g. to check they are well formed).

Addresses #9, but doesn't resolve it because this doesn't include spec.

2022-06-08 19:34 UTC, marsella commented on src/lib.rs
> +mod localclient;
Fix naming: should be [snake case per Rust convention](https://rust-lang.github.io/api-guidelines/naming.html).

2022-06-10 09:00 UTC, gijsvl commented on src/localclient.rs
> +//! Public API for the DAMS local client library.
I would love to see tests for each of the APIs, that now just verify that the todo-macro is called. This will force us to make sure there are still tests when we implement these.

2022-06-10 09:00 UTC, gijsvl commented on src/keys.rs
> +struct DigitalAssetKey<P, R>
We maybe want an abstract Key trait? This allows us to define different types of keys easily afterwards and this van make our API more general.

2022-06-10 09:00 UTC, gijsvl commented on src/keys.rs
> +pub struct KeyInfo {
Do we want some link to the owner? A userId or something that allows us to find keys based on the user... Or maybe this is going to be part of DigitalAssetKey's permissions and restrictions? On the other hand this is going to be the case for every type of key. Another option is to store this somewhere separately (userid-keyid). And now I come to think of it this might be troublesome for some sort of anonymity...

2022-06-10 09:00 UTC, gijsvl commented on src/keys.rs
> +pub struct KeyTag(String);
Are these going to be unique? For each user or globally? I understand that the KeyId is supposed to be the unique identifier, but the question is based on what we are going to search for keys, I suppose this tag as well. How do we envision that?

2022-06-10 13:05 UTC, marsella commented on src/keys.rs
> +pub struct KeyTag(String);
I intend the `KeyId` to be unique, and the `KeyTag` to be human-readable, maybe unique among a single user's keys. All lookups will be done with the`KeyId`, but a user can get a list of all their keys and distinguish between them with the `KeyTag` more easily than remembering random ids.

2022-06-10 16:12 UTC, indomitableSwan requested changes
This is a good start!

Major comments:
1. We need to do some more legwork on the digital asset key abstraction. I think it would help to start fleshing out the low-level abstractions in code to help think through this concretely. 
2. We should pair references to multiple servers with TODO flags rather than have inconsistent support for multiple servers and create an epic for extension to multiple servers.
3. If we aren't handling local generation functionality in this pass, we should create an epic to track this as a separate set of tasks.
4. If we aren't handling arbitrary secrets or signing secrets in this pass, we should create an epic to track these as separate sets of tasks.
5. I don't see any requirements or assumptions on the consuming application. We should attempt to collect these requirements and put them in the spec, as well as referencing the requirements where appropriate. A quick example that comes to mind is around UUIDs for users --- are they coming from the consuming application? Or are we creating and passing our own UUIDs to the consuming application? My understanding so far has been the former.
6. Are we happy with the internal module structure outlined here? Reflecting back on our internal development goals, we should collect and organize the requirements for the API and session types and organize into reasonable modules.
7. Re: specification work. I think it's useful to start scoping out a developer guide for this library at this point. We should aim for a useful specification document that does not duplicate too much from the code base, but allows for understanding of how the described underlying protocols are realized in the codebase.
8. We should establish a process for marking and explaining TODOs in the comments and start to apply this consistently. Because there are a lot of TODOs. Perhaps we need an adjustment to the development process guidelines/definition of done about this.

Nits:
- The `localclient` module is private. When I build with` --document-private-items`, there are some doc errors that need to be resolved for it to build properly. Would request a read-through of the documentation for completeness, punctuation, etc., before resubmission.

2022-06-13 13:46 UTC, marsella commented on src/keys.rs
> +struct DigitalAssetKey<P, R>
I'm inclined to wait to define that trait until we know what our other high level keys are and what the shared behaviors will be.

2022-06-13 15:04 UTC, marsella commented on src/keys.rs
> +/// Unique identifier for a key.
Added #24 to address this and switched KeyId to an empty struct (we can decide the specific instantiation when someone takes on the new issue).

2022-06-13 15:34 UTC, marsella commented on src/keys.rs
> +/// how much power the owner has delegated to another entity.
Fixed the specific terminology issues and added some `TODO`s.

2022-06-13 15:52 UTC, marsella commented on src/keys.rs
> +struct Delegated {
I added a TODO but I am not sure what the best way to describe it here will be - is it a global config value? Do we support a front end where an asset owner delegates keys to multiple different delegated signing authorities? I am not inclined to fill in a `DelegatedId` until we have answers to this.

2022-06-13 20:01 UTC, marsella commented on src/keys.rs
> +/// Specification of a user policy.
I took a stab but now I'm not quite sure how user policies work. My existing assumption was that the policies define some conditionals that, if they fail, trigger the key servers to require additional authentication directly from the user to continue with a transaction approval request (specifically in the case of a delegated key). But this doesn't make sense in the context of self-custodial keys, where the user already manually approved the TAR.

2022-06-13 21:16 UTC, marsella commented on src/localclient.rs
> +pub struct SessionConfig;
Do you mean the dialectic / double-encryption project or something else?

2022-06-13 21:24 UTC, marsella commented on src/localclient.rs
> +//! Public API for the DAMS local client library.
I am happy to fix the name if someone is willing to brainstorm a better idea with me.

2022-06-13 21:27 UTC, marsella commented on src/localclient.rs
> +/// [`Error::ExpectedDelegatedKey`].
Yeah, I will reword this comment to reflect that. I am not sure how to best handle future-phase features beyond leaving them as `todo`s and potentially adding "dummy" implementations in a branch if we want to do a demo. If we do a tagged release of a phase and don't want to release panicking `todo` functions, we can feature-gate at that time.

2022-06-13 21:31 UTC, marsella commented on src/localclient.rs
> +/// defined by the open `session`).
The user id isn't an explicit parameter here, it's something you can get out of the session. My thought was to avoid over-specifying who the user is (e.g. what if the session has a different user from the parameter?) but per a discussion last week, I will just add the user id as a parameter here and we can double-check that it's the person we expect it to be.

What format do you want more information on?

2022-06-13 21:37 UTC, marsella commented on src/localclient.rs
> +pub fn create_digital_asset_key(
Do you mean an ID for the entity that originated this request? Or the application for which it will be used? I can reuse the `OriginatorId` we have for determining who created a TAR, but not sure if they're quite the same.

2022-06-13 21:38 UTC, marsella commented on src/localclient.rs
> +pub fn retrieve_public_key(session: Session, key_id: &KeyId) -> Result<KeyInfo, Error> {
I would prefer not to allow that. I think that key tags will be a human feature to make it easier for people to interact with the front end, but that key ids are the final determinant for identifying a key. So, if the user clicks a button on the app based on the key tag, the app should internally look up the corresponding key id and make this request with it.

2022-06-13 21:58 UTC, marsella commented on src/localclient.rs
> +pub fn retrieve_audit_log(session: Session, key_id: Option<&KeyId>) -> Result<String, Error> {
I'm not sure which part of this is not in line with the spec. Changed `user` -> `asset owner` in the docs, is there another item here?

2022-06-13 21:59 UTC, marsella commented on src/localclient.rs
> +pub fn set_user_key_policy(
I'm not sure which part of this is out of line. Do you want me to rename something like `set_asset_owner_key_policy`?

2022-06-13 22:15 UTC, marsella commented on src/transaction.rs
> +/// Unique ID for the entity that originates a transaction.
I am not sure. I was thinking it's either a game or an individual user, but we could potentially reuse this for delegated entities / service providers as well.

2022-06-13 22:27 UTC, marsella commented on src/transaction.rs
> +/// formed by the specified [`OriginatorId`].
I thought the originator was the entity that created the transaction, which might be a different party from the service provider or asset owner (e.g. a game). The TAR will be submitted to the key servers from one of those two parties.

I added this assumption in the `transaction_approval_request` _function_ in `local_client.rs`, but I'm not sure it belongs here.

The TODO extension is something I would put in the key server API (e.g. when this request is received, it should be compared to a whitelist and rejected if it's from an inappropriate entity). 

I can try to add more assumptions, but I prefer to put the ones about how the TAR is used and when it should be rejected belong on the API calls, not on the object itself.

2022-06-14 19:17 UTC, marsella commented on src/transaction.rs
> +pub struct TransactionApprovalRequest {
As above - I think not. The calling application can show key tags to users, but will use the id as the unique identifier for the API.

2022-06-14 19:26 UTC, marsella commented on src/localclient.rs
> +    /// Register a new user who has not yet interacted with the service.
It does. I am actually a bit conflicted about whether it's necessary to keep `open` and `register` separate - it might be easier to have `open` automatically register the user if they have not already done so.

2022-06-14 19:39 UTC, indomitableSwan commented on src/keys.rs
> +/// Specification of a user policy.
Your existing assumption is correct and I intended this for self-custodial keys as well. Think about it like adding additional layers of protection for extremely sensitive operations. e.g., If I'm emptying out my bank account, also please collect my fingerprint instead of just my password, would you please?

2022-06-14 19:47 UTC, indomitableSwan commented on src/localclient.rs
> +pub fn transaction_approval_request(
I don't have a preference.

2022-06-14 19:58 UTC, indomitableSwan commented on src/localclient.rs
> +pub fn set_user_key_policy(
I'm not in love with the naming in the spec here on this one. I think everywhere in the draft this is referenced as a "user-set policy". But whatever this object is we should reference it consistently, i.e., either it's a "user key policy" or a "user policy", or "X" where X is something better, in both places.

2022-06-14 19:59 UTC, indomitableSwan commented on src/localclient.rs
> +pub fn set_user_key_policy(
(not sure it's very consistent to use the word 'user' here, as you point out)

2022-06-14 20:06 UTC, indomitableSwan commented on src/transaction.rs
> +/// formed by the specified [`OriginatorId`].
I'm suggesting we simplify by leaving checking/tracking originators up to the A&A code. If we were building our own complete e2e product, I'd still consider handling this extension on our version of the A&A code and not the key servers themselves. (Not saying I'm necessarily right about that, but I don't think we have to decide this today.)

This may be an oversimplification. But I'd rather wait for a concrete use case to create something more nuanced/complicated here.

2022-06-14 20:08 UTC, indomitableSwan commented on src/transaction.rs
> +pub struct TransactionApprovalRequest {
OK. If we settle on this route then tracking this mapping should be described as a requirement for the calling application in the spec repo, shouldn't it?

2022-06-14 20:19 UTC, indomitableSwan commented on src/localclient.rs
> +    /// Register a new user who has not yet interacted with the service.
I'm not sure if there is any reason to keep these separate. Under the hood, this is OPAQUE, and there are different security requirements for the underlying communication channel for OPAQUE registration vs the AKE. But we intend to still use the same server-authenticated, confidential channel with integrity for the AKE. Maybe @gijsvl has thoughts on this?

2022-06-14 21:07 UTC, marsella commented on src/localclient.rs
> +    /// Open a new session for a registered user.
I added some notes about properties on the `Session` type itself, but I'm not that confident that I got them all. 

I am not sure what the object itself will consist of. One very plausible option in my mind is a list of dialectic channels, open to each server. When you call an API function, it'll use the appropriate channels to talk to any key servers it needs to. Even if it ends up being something else, I prefer to have a `Session` type to abstract away the concept of "send a message to an internal DAMS component". 

Not listed in the `impl Session` block are a variety of private-to-module functions that will send or receive messages on the channel, or at least give access to the internal fields that allow sending and receiving. (NB: the `Session` parameters to all these functions might need to be a mutable reference or something).

2022-06-14 21:09 UTC, marsella commented on src/localclient.rs
> +impl Session {
Does this need to be a TODO flag? Authenticated communication is the entire functionality of a `Session`. I don't think it needs to be noted separately.

2022-06-14 21:09 UTC, marsella commented on src/localclient.rs
> +/// Communication session with a set of key servers.
Added more details, but let me know if it still doesn't make sense.

2022-06-14 21:41 UTC, marsella commented on src/localclient.rs
> +/// the given ID.
The format will the `TransactionSignature` type, so any special notes about format can go there. I'm not sure what detail we would add at this point - I haven't thought about format at all.

I also don't know when we'll retrieve it. You had written somewhere
> This may be useful in allowing the end customer to submit their own transactions. For example, digital asset keys may not be blockchain-related, and it may be appropriate for end customers to have direct access to signatures generated by the DAMs.

2022-06-14 21:42 UTC, marsella commented on src/localclient.rs
> +/// and compatible with the specified blockchain.
The return type of this function is `Result<(), Error>`. If everything worked, you'll get `Ok(())`, which is the "success indicator" we talked about elsewhere. If something went wrong, you'll get an error.

2022-06-14 21:44 UTC, marsella commented on src/keys.rs
> +/// Convenient grouping of the public components of a digital asset key pair.
Added `UserId` per diagram discussion with Vidya the other day.

2022-06-15 17:43 UTC, indomitableSwan requested changes
- Do we want to have TODOs linked to explicit epics/issues?
- I'm finding session handling at the application layer confusing at this point. Specifically, I'd like to better understand how we're tying key requests to sessions. 
- In terms of key requests, it seems as though we're already trying to abstract across the remote client too, ie we're thinking ahead and writing functions that will work for both. Am I misunderstanding this?

2022-06-15 21:23 UTC, marsella commented on src/keys.rs
> +/// This represents a full key pair.
Added a new `crypto` module and put some secret material in here.

Operations on a digital asset key will live here, probably. There aren't that many actions that you can take with a "full" key. Operations on a digital asset key share will also live here, but the meat of the cryptography will live in the `crypto` module. I expect the `crypto` module will include the cryptographic operations and intermediate states (e.g. steps in a protocol), while this module will call those functions and connect them via an actual distributed protocol execution.

2022-06-15 21:26 UTC, marsella commented on src/localclient.rs
> +/// A `Session` is an abstraction over a set of mutually authenticated
Correct. This is the output of a registration session, but the initial communication in that session is not via a `Session`. It's via whatever the underlying networking layer is.

2022-06-15 21:27 UTC, marsella commented on src/localclient.rs
> +/// key servers are specified in the [`SessionConfig`]. An open `Session` is
Sure, but when that changes, I'm hoping to just update the internals of `Session` and not have to change too much about the other functions. That might not work though, I haven't thought this abstraction through very well.

2022-06-16 15:30 UTC, marsella commented on src/localclient.rs
> +//! Public API for the DAMS local client library.
Added!

2022-06-17 14:32 UTC, marsella commented on src/client.rs
> +    key_mgmt::client as keymgmt,
Not sure, but I changed it to `key_mgmt` across the board (both this alias and the name of the library itself).

2022-06-17 14:33 UTC, marsella commented on src/keys.rs
> +/// Unique identifier for a key.
Yeah. I moved it to keys -- because a digital asset key is meaningless without a digital asset owner -- but I'm not sure that's quite the right place either.

2022-06-17 14:35 UTC, marsella commented on src/keys.rs
> +/// Convenient grouping of the public components of a digital asset key pair.
Good catch. I guess non-secret. I imagine this information will be accessible by the asset owner and any delegated party and maybe the asset fiduciaries and parties who originate transactions. But that's technically not public.

2022-06-17 14:35 UTC, marsella commented on src/keys.rs
> +/// This represents a full key pair.
The crypto module is going to need a lot of review, I think. Another option is that I remove it here and we make it a separate PR.

2022-06-17 15:12 UTC, marsella commented on src/localclient.rs
> +pub struct SessionConfig;
I made #30 about designing this better. I didn't write about networking protocols in that issue.

2022-06-17 15:36 UTC, marsella commented on src/localclient.rs
> +/// key servers are specified in the [`SessionConfig`]. An open `Session` is
Anyway, I will update docs here and elsewhere to clarify.

2022-06-17 15:40 UTC, marsella commented on src/localclient.rs
> +/// the local client, or be a system-wide configuration).
Yeah. I was trying to capture something from a different comment in the first round, but I don't think it's helpful here.

2022-06-17 15:41 UTC, marsella commented on src/localclient.rs
> +/// Retrieve the signature generated by the transaction approval request (TAR)
Okay, yeah. I like the plan of leaving caching to the calling application.

2022-06-17 15:43 UTC, marsella commented on src/localclient.rs
Yeah, there are a couple of options, like
- pick a random key server
- if there's a middleman between client and key servers, maybe they cached the non-secret information and you can get it from them
- pick multiple key servers and make sure you have consensus

2022-06-17 16:23 UTC, marsella commented on CONTRIBUTING.md
> +Issues are described in the issue tracker, but there is also supporting inline documentation noting the specific location of various types of problems in the code. These are marked as `TODO (optional
Do you prefer to keep these modifiers inline or should I just add the issue number and leave it at that? I am not convinced these are well described.

2022-06-17 16:24 UTC, marsella commented on src/localclient.rs
> +/// than a generic `String`). TODO (feature): add an optional date range
@indomitableSwan I made #31 and #32 to cover these issues. I'm inclined to remove the inline TODOs since I don't think the extra context here is that valuable. Do you object?

2022-06-17 19:00 UTC, marsella commented on src/transaction.rs
> +pub struct TransactionApprovalRequest {
Decided not to go this route after our conversation. Switched `KeyId` to `Indicator`, which is either an `Id` or a `Tag`.

2022-06-17 19:40 UTC, marsella commented on src/localclient.rs
> +impl Session {
It might be part of session config, I'm still very fuzzy on how this abstraction is going to work. I made #30 to capture some of my confusion.

2022-06-17 19:42 UTC, marsella commented on src/keys.rs
> +struct Delegated {
Yeah, I agree with your assessment and I think it is reasonable to wait to define a delegated ID, since in this version there is only one possible delegated party. I tried to capture this in #27.

2022-06-17 19:44 UTC, marsella commented on src/localclient.rs
> +pub fn retrieve_public_key(session: Session, key_id: &KeyId) -> Result<KeyInfo, Error> {
Yeah, that makes sense. I updated across the API to take either a key id or a tag.

2022-06-17 19:44 UTC, marsella commented on src/transaction.rs
> +/// Unique ID for the entity that originates a transaction.
Removed originator id for now.

2022-06-17 19:48 UTC, marsella commented on src/localclient.rs
> +/// and compatible with the specified blockchain.
Updated this to return a `KeyInfo`, with the public key and newly generated ID.

2022-06-24 11:50 UTC, indomitableSwan requested changes
There are a couple outstanding TODOs in `keys.rs`:
- Documentation nit in L5 (the documentation is outdated).
- See individual comments around L34.

Otherwise the comments are just comments.

There is also an issue with the CI that causes the build to fail locally but not on github because of documentation line wrapping.
<img width="998" alt="Screen Shot 2022-06-24 at 7 41 42 AM" src="https://user-images.githubusercontent.com/5496520/175527445-729c2a83-192f-421a-87df-ed668b99ac45.png">

2022-06-24 11:50 UTC, indomitableSwan commented on src/keys.rs
> +/// This represents a full key pair.
I see that we have removed some of this to #19, which is an epic. I am going to make a few comments about this here in response to what you have written, but I would like to see specific issues for the digital key abstraction tagged under the #19 epic that capture this discussion. (As a side note, looking at #19, it seems to be confused about its purpose and is trying to both handle underlying cryptographic operations and the DAMS abstractions -- which is it? Because this discussion is about the latter.)

Now that I understand that you did intend to capture a "full key pair" here, in the sense of containing secret material, I'm even more confused why secret material isn't specified as part of this object. The abstraction we have left here is very confusing to me: it doesn't satisfy the use case for `local-client` and again, seems to be attempting to solve a more general problem than what was needed to capture the local client abstractions. Specifically:
- The client will not _have_ a full key pair, will it? (At least not with our current set of operations?)
- The client may not even have a key share.
- So what object does the client have that represents the information the client has about their key? Is it just `Key-info`? This seems like the question that ought to have had an answer in this PR, or at least a placeholder. I do not want to hold up this PR any longer though, so I recommend writing up a distinct issue for this particular point.

2022-06-24 11:50 UTC, indomitableSwan commented on src/keys.rs
> +//! and machine- and human-readable tags for keys.
We removed the key tags.

2022-06-24 11:50 UTC, indomitableSwan commented on src/localclient.rs
There is also a possibility that there is local storage of this information and a backup at the server(s).

2022-06-24 11:50 UTC, indomitableSwan commented on src/transaction.rs
> +pub struct TransactionApprovalRequest {
To confirm for the latest pass: we removed `Tag`, so now we have a `KeyId`.

2022-06-24 11:50 UTC, indomitableSwan commented on src/keys.rs
> +/// This represents a full key pair.
A minor nit: we should also clarify what "full key pair" means in the documentation.

2022-06-24 11:50 UTC, indomitableSwan commented on CONTRIBUTING.md
> +Issues are described in the issue tracker, but there is also supporting inline documentation noting the specific location of various types of problems in the code. These are marked as `TODO (optional
I am OK with the current approach.

2022-06-24 14:57 UTC, marsella commented on src/keys.rs
> +/// This represents a full key pair.
Okay, yes. This object is not actually used in any of the local client APIs. I think I defined it early on to help organize my thinking around the other key-like types and traits, but it won't be used by the local client until we add key export. If you'd like, I can make it private or remove it completely from this code.

The objects that the client can get with this API are just `KeyInfo`, `TransactionSignature`s, and the audit log. Do you want me to try to explain this better at the module level documentation?

There's no secret material here because I think those types would be defined in the underlying (generalized) cryptographic library and I don't want to try to define that right now. But yes, I was confused about which library #19 was trying to describe. I will clarify that issue.

2022-06-24 19:21 UTC, marsella commented on src/localclient.rs
Added an explicit note about the range of possibilities.

2022-06-24 19:22 UTC, marsella commented on src/keys.rs
> +/// This represents a full key pair.
Noting: I made `DigitalAssetKey` private, so it's not available via the public local client API.

2022-06-24 21:07 UTC, marsella commented on src/keys.rs
> +pub struct KeyTag(String);
Note: we ended up removing KeyTags.

2022-06-24 21:26 UTC, marsella commented
Fixed the CI thing - I accidentally pushed some local changes to my `rustfmt.toml`. They are now reverted.

2022-06-27 14:20 UTC, indomitableSwan approved these changes

2022-06-27 18:02 UTC, merged