Implement remote signing key generation #187
boltlabs-inc/key-mgmt pull request #273
Opened 2022-10-06 21:39 UTC by picklenerd

Closes #187

2022-10-12 20:28 UTC, picklenerd commented on lock-keeper/src/types/database/secrets.rs
> +    pub secret: Vec<u8>,
@indomitableSwan  https://www.youtube.com/watch?v=3tmd-ClpJxA

This is awful and wrong but I don't know of a good way to encrypt this with what we have right now without having the encryption key stored in the same database table.

2022-10-12 20:36 UTC, picklenerd commented on lock-keeper-key-server/src/database/secrets.rs
> +        let stored_secret = ServerGeneratedSecret::new(secret.into(), key_id);
@indomitableSwan @marsella This is where the storage type for the `SigningKeyPair`. It takes the raw `SigningKeyPair` bytes and stores them directly for now.

2022-10-12 20:39 UTC, vidyaap commented on lock-keeper-key-server/src/database/secrets.rs
> +        let stored_secret = ServerGeneratedSecret::new(secret.into(), key_id);
FYI, I think my import code will help will this! I can make a draft PR in a second so you can see

2022-10-12 20:41 UTC, vidyaap commented on lock-keeper-key-server/src/database/secrets.rs
> +        let stored_secret = ServerGeneratedSecret::new(secret.into(), key_id);
Or actually, it's Marcella's `Import` type and related code.

2022-10-13 13:42 UTC, indomitableSwan commented on lock-keeper/src/types/database/secrets.rs
> +    pub secret: Vec<u8>,
> https://www.youtube.com/watch?v=3tmd-ClpJxA

Hmm. Yes. This is why I had been thinking that leaving things unencrypted for now would not be the worst idea: just as broken, only more evidently so.

2022-10-13 14:41 UTC, picklenerd commented on lock-keeper/src/types/database/secrets.rs
> +    pub secret: Vec<u8>,
Ok cool. We can leave this for now and come back to it later! Resolving.

2022-10-13 15:54 UTC, picklenerd commented on lock-keeper-key-server/src/database/secrets.rs
> +        let stored_secret = ServerGeneratedSecret::new(secret.into(), key_id);
Ok I updated the code to use the same types from your PR.

2022-10-13 19:54 UTC, marsella requested changes
There's a missing server-side check that the user id matches the user making the request. My other comments are less important.

This was very easy to review -- all the refactoring that you all have done has been very successful in making this super clearly delineated.

2022-10-13 19:54 UTC, marsella commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
todo: I expected a check here that the `request.user_id` matches the account from (I think) the `Context` -- e.g. to prevent user A authenticating as themselves, but then creating a key for user B.

2022-10-13 19:54 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
todo: I'd like documentation on this type to the effect of "it's serializable for the database, but don't send it in the clear over a network". Or just the latter half if you think it's more reasonable.

2022-10-13 19:54 UTC, marsella commented on lock-keeper/src/types/database/secrets.rs
> +}
thought: This structure seems like every time we add a new type of stored secret, we have to update our retrieve code to look through another list. I know there's a plan to discuss better database structure, but is it a worthwhile intermediate step to pull out the key ids from this so it's easier to search on them? Like

```rust
// don't use this name
pub struct AnyKindOfSecret {
    key_id: KeyId
    retrieved: bool,
    secret: StoredKind,
}
enum StoredKind {
    EncryptedSecret(Encrypted<Secret>),
    EncryptedSigningKeyPair(Encrypted<SigningKeyPair>),
    SigningKeyPair(SigningKeyPair),
}
```

2022-10-13 19:54 UTC, marsella commented on lock-keeper-tests/src/end_to_end.rs
> +        Test::new(
todo: Can you add a test to retrieve a remote generated secret? Is that a separate issue?

2022-10-13 20:04 UTC, picklenerd commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
I can add that.

I think these requests containing user_ids will be redundant once we have sessions. If the user is authenticated and has a session key that decrypts the message correctly, then we know their user_id and we know that they're the one that authenticated.

2022-10-13 20:05 UTC, picklenerd commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
I think we could do bson conversions instead of serialize/deserialize. I'll investigate.

2022-10-13 20:08 UTC, vidyaap commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
Should that check be added in the other requests too, until we have sessions? If so, I'm happy to make those changes to all the endpoints at once, if that's easier?

2022-10-13 20:09 UTC, picklenerd commented on lock-keeper/src/types/database/secrets.rs
> +}
We avoided the enum because we don't want to add error handling for situations where you need an `EncryptedSecret` but you have to make sure it's not the other variants. Having it this way means that the types are always correct for the secret you're trying to retrieve. If the database data gets corrupted and the data for a given key id changes to a different type, the whole user will fail to load instead of having a silent failure that doesn't show up until the key is retrieved.

This struct is temporary until we have a more permanent solution for how we represent secrets in the database.

2022-10-13 20:10 UTC, picklenerd commented on lock-keeper/src/types/database/secrets.rs
> +}
Alternatively we could remove the guarantee that the caller gets what they asked for and force them to check the type.

2022-10-13 20:11 UTC, vidyaap commented on lock-keeper/src/types/database/secrets.rs
> +}
Also wanted to throw in there that because of the types, retrieving each type of secret has its own function right now, so we can specify which one of the lists to look through in each.

2022-10-13 20:13 UTC, picklenerd commented on lock-keeper-tests/src/end_to_end.rs
> +        Test::new(
I don't think there's an issue for that since I don't think retrieving them is part of our API. We'll be able to test this more thoroughly when we do the remote signing issue but this feature is a prerequisite for that issue.

2022-10-13 20:15 UTC, picklenerd commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
If it's missing from all of them I think we should just deal with them once we have our basic sessions working later in this phase.

2022-10-13 20:19 UTC, picklenerd commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
On second though,  I think it would be a better idea to have a temporary type that represents an encrypted version of this. I really don't want to implement any conversions on this type that would allow it to be used improperly.

2022-10-13 20:53 UTC, picklenerd commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
Ok I updated this with a really simple type that has the same data, is convertible from a `SigningPublicKey`, and implements serialize/deserialize. It has a very long and ugly name so that it stands out.

2022-10-13 21:31 UTC, marsella commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
Jordan: are you suggesting the messages with user ids would not have user ids in them any more? Like, you would send a unit struct of `RequestRemoteGenerate` and the server would pull the user id from the authentication?
If not, then this is a separate issue -- you can have an authenticated channel for user A and still send a user id over it that corresponds to user B.

Vidya: yes, any request that starts with sending a user id should make sure that user id matches the authenticated user (with some caveat for the future of passive requests where the requesting client will be a Service Provider making requests on behalf of a user. But I don't think we need to build for that now).

2022-10-13 21:48 UTC, picklenerd commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
Yeah I think they'd have to have some sort of marker in them to indicate the message type but they wouldn't need to send a user id since this will be available in the session. If the authenticated user_id is the only valid user_id, then having the user send their user_id doesn't do anything.

2022-10-14 13:52 UTC, marsella commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
Okay, that sounds good to me. Is this plan explicitly documented in an issue yet?

2022-10-14 13:52 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
Thanks, I like this plan!

2022-10-14 13:54 UTC, marsella commented on lock-keeper/src/types/database/secrets.rs
> +}
Okay, cool. That sounds good to me. 

> Alternatively we could remove the guarantee that the caller gets what they asked for and force them to check the type.

This seems more mistake-prone. What you have planned makes sense to me.

2022-10-14 14:04 UTC, marsella commented on lock-keeper-tests/src/end_to_end.rs
> +        Test::new(
Retrieval of any kind of secret is definitely in the spec. Do you mean that it's not part of this phase?

2022-10-14 14:18 UTC, vidyaap commented on lock-keeper-tests/src/end_to_end.rs
> +        Test::new(
I don't think retrieval of signing keys is in this phase, but export is, and the way I wrote it is just a wrapper around retrieval (same as arbitrary secrets). I'm not sure about the accuracy of the retrieval I made for signing keys because we didn't talk about including it in the phase, but pending fixes there, it should be enough to add the test you're talking about.

2022-10-14 14:28 UTC, picklenerd commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
https://app.zenhub.com/workspaces/bolt-team-60886be9e01f13000e361d92/issues/boltlabs-inc/key-mgmt/289

2022-10-14 14:54 UTC, marsella commented on lock-keeper-key-server/src/operations/remote_generate.rs
> +        let request: client::RequestRemoteGenerate = channel.receive().await?;
Thank you!

2022-10-14 15:52 UTC, merged