Don't call local_storage_bytes in None case #320
boltlabs-inc/key-mgmt pull request #322
Opened 2022-10-27 15:26 UTC by vidyaap

Closes #320 

This was on me! I had the conversion to bytes outside of the match so it was trying to convert blank key material into bytes.

Also addresses part of #317 to move the audit event log check in the e2e tests to the end.

2022-10-27 19:27 UTC, gatoWololo requested changes
The PR looks good. I left some comments for refactoring the nested matching, which I think makes it more obvious what is going on. I tried to post my refactoring steps, so hopefully it is clear how I arrived at the final version. Instead of just posting the final version. Lmk if you have questions!

2022-10-27 19:27 UTC, gatoWololo commented on lock-keeper-tests/src/end_to_end.rs
>                  }
I'm finding this logic here a bit hard to follow. I cleaned it up a bit by getting rid of the intermediate string conversions:
```rust
match outcome {
                Ok(()) => match &expected_outcome.expected_error {
                    Some(err) => {
                        anyhow::bail!("Unexpected success, expected: {err:?}")
                    }
                    None => {
                        self.check_audit_events(&self.config, EventStatus::Successful, &op)
                            .await
                    }
                }?,
                Err(e) => {
                    match &expected_outcome.expected_error {
                        Some(expected) => {
                            if expected.to_string() != e.to_string() {
                                anyhow::bail!("Incorrect error. expected {expected:?}; got {e:?}")
                            }
                        }
                        None => anyhow::bail!("Unexpected error {e}"),
                    }
                    self.check_audit_events(&self.config, EventStatus::Failed, &op)
                        .await?;
                }
            }
```

2022-10-27 19:27 UTC, gatoWololo commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
It looks like this line is only ever called in the Some arm of the match statement, when the `expected_string == error_string`. This isn't obvious from the logic. We should bring that into the match arm:
```rust
Err(e) => match &expected_outcome.expected_error {
                    Some(expected) => {
                        if expected.to_string() != e.to_string() {
                            anyhow::bail!("Incorrect error. expected {expected:?}; got {e:?}")
                        }
                        self.check_audit_events(&self.config, EventStatus::Failed, &op)
                            .await?;
                    }
                    None => anyhow::bail!("Unexpected error {e}"),
                },
```

2022-10-27 19:27 UTC, gatoWololo commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
Then I collapsed the match statements to try making it more clear what is going on:
```rust
match (outcome, expected_outcome.expected_error) {
                (Ok(()), Some(unexpected_err)) => {
                    anyhow::bail!("Unexpected success, expected: {:?}", unexpected_err);
                }
                (Ok(()), None) => {
                    self.check_audit_events(&self.config, EventStatus::Successful, &op)
                        .await?;
                }
                (Err(e), Some(expected_err)) => {
                    if expected_err.to_string() != e.to_string() {
                        anyhow::bail!("Incorrect error. expected {expected_err:?}; got {e:?}");
                    }
                    self.check_audit_events(&self.config, EventStatus::Failed, &op)
                        .await?;
                }
                (Err(e), None) => anyhow::bail!("Unexpected error {e}"),
            }
```

(Final version)

2022-10-27 20:33 UTC, picklenerd commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
Oh yeah I see it now, since the other branch returns an error.

2022-10-28 18:10 UTC, vidyaap commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
Thanks for this breakdown!! I hate to say it though, but the e2e test refactor PR (#325) gets rid of the match anyway 😅

2022-10-28 18:12 UTC, gatoWololo commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
After talking to Jordan, I am rewriting the Display function as `local_storage_bytes` is broken. So I actually don't think we need anything from this PR? :grimacing:

2022-10-28 18:13 UTC, vidyaap commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
lol no worries, if that's definite, I can just close this PR.

2022-10-28 18:24 UTC, gatoWololo commented on lock-keeper-tests/src/end_to_end.rs
> +                        .await?;
Yeah, that sounds good! Thanks.

2022-10-28 18:29 UTC, vidyaap commented
Closing this because the CLI issue and the E2E issue are being fixed in #300 and #313 respectively.

2022-10-28 18:29 UTC, closed without merging