Adding an encryption tunnel using session_key
boltlabs-inc/key-mgmt pull request #373
Opened 2022-11-21 15:21 UTC by gijsvl

Closes #327
Closes #260

2022-11-22 11:56 UTC, gijsvl commented
For the reviewers:
- @marsella I liked your idea of using custom derive macros. However, custom derive macros (or procedural macros) need to be in their own crate. Therefore, we would have to create a separate crate (possibly withing our repo) to provide these custom derive functions. We can still do this in the future, but I opted not to do this now. To avoid having to pass the session key every time in the `send` (and `receive`) function, I've changed the channel to contain an optional `session_key`, this makes it an (un)authenticated channel depending on the availability of the `session_key`. Moreover, I've added a Trait `ShouldBeAuthenticated` that needs to be added to objects to answer with true or false depending on the fact that an object need to be sent over an authenticated channel or not. This is added through the already existing macro, and I've created a new macro for authenticated objects (as you will see). Let me know if you have any concerns about this approach, or other comments...
- @picklenerd As discussed I've added an enforcement on the objects (as explained above using `ShouldBeAuthenticated`). Moreover, I've been able to use the same rng after all, so there is no issue of creating a new rng everytime. Let me know if you have any other comments.

2022-11-22 14:03 UTC, jwantz commented
@gijsvl: I believe this will also be a breaking change in the sense of backwards compatibility. That is, a v0.3 server will not be able to communicate with a v0.2 client. If you agree, then we should also add this to the readme and the release notes.

2022-11-23 00:22 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> +            _ => return Err(LockKeeperClientError::AuthenticatedChannelNeeded),
Can we list the error cases explicitly here? I want to make sure these functions show an error if a new `ClientAction` is added.

2022-11-23 00:22 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> +            _ => return Err(LockKeeperClientError::UnauthenticatedChannelNeeded),
Same here

2022-11-23 00:25 UTC, picklenerd commented on lock-keeper/src/crypto/generic.rs
> +    // #[cfg(test)]
Just flagging this.

2022-11-23 00:50 UTC, picklenerd commented on lock-keeper/src/lib.rs
> +            }
I'm wondering if there's a way we can do this without duplicating the code. I was playing around and came up with this:

```rust
/// Common implementation for `impl_message_conversion` variants.
#[macro_export]
macro_rules! impl_message_conversion_internal {
    ($message_type:ty) => {
        impl TryFrom<$crate::types::Message> for $message_type {
            type Error = $crate::LockKeeperError;

            fn try_from(value: $crate::types::Message) -> Result<Self, Self::Error> {
                Ok(serde_json::from_slice(&value.content)?)
            }
        }

        impl TryFrom<$message_type> for $crate::types::Message {
            type Error = $crate::LockKeeperError;

            fn try_from(value: $message_type) -> Result<Self, Self::Error> {
                let content = serde_json::to_vec(&value)?;

                Ok($crate::types::Message { content })
            }
        }
    };
}

/// Generates `TryFrom` implementations to and from the `Message` type for a
/// given list of types.
#[macro_export]
macro_rules! impl_message_conversion {
    (unauthenticated, $($message_type:ty),+) => {
        $(
            $crate::impl_message_conversion_internal!{$message_type}

            impl $crate::infrastructure::channel::ShouldBeAuthenticated for $message_type {
                fn should_be_authenticated(&self) -> bool {
                    false
                }
            }
        )+
    };
    (authenticated, $($message_type:ty),+) => {
        // use $crate::impl_message_conversion_internal;
        $(
            $crate::impl_message_conversion_internal!{$message_type}

            impl $crate::infrastructure::channel::ShouldBeAuthenticated for $message_type {
                fn should_be_authenticated(&self) -> bool {
                    true
                }
            }
        )+
    };
}

```

Which looks like this in use:

```rust
    impl_message_conversion!(unauthenticated, AuthenticateStart, AuthenticateFinish);
    impl_message_conversion!(authenticated, SendUserId);
```

There's probably a better way to do this but it's late so this is what my tired brain did 😆

2022-11-23 00:51 UTC, picklenerd commented on lock-keeper-key-server/src/server/operation.rs
> +    async fn handle_authenticated_request(
Can we break these up in a way that removes the duplicate code?

2022-11-23 00:52 UTC, picklenerd commented on lock-keeper/src/infrastructure/channel.rs
>  }
Can we make this a hard requirement of the `Operation` trait in the server?

2022-11-23 17:00 UTC, marsella requested changes
Thanks for this PR!

First off: perfectly reasonable to not do derive macros in this PR. It's already quite hefty :) and that will be fine to layer on at a later date.

Putting the session key into the channel also sound reasonable to me. It's also nice to be able to use the unauthenticated channel directly to send `Encrypted<Message>`! Architecture-wise, a channel lives only for the length of a request, right? So this will make sure that two parties can finish a single request, but it still leaves decisions about overall session management / expiration to the server-side storage. 

For the overall design, it sounds like the guarantee is, "if a channel has a session key and a given message should be authenticated, it will be authenticated." I was wondering if we can enforce something stronger: "if the channel has a session key, every message sent over it is authenticated." 

This seems hard. The goal would be misuse resistance -- to encrypt stuff by default and not require the developer to correctly flag individual protocol messages as "auth" / "noauth". Is it possible to design some type-level constraint that will cause a compile error if the developer tries to send a message that isn't explicitly "send me in the clear" over a channel that supports authentication?

I think it's worth thinking about. The current version is OK since a given protocol message doesn't _default_ to unauthenticated. The developer always has to make a decision. But it would be cool to have unauthenticated messages be the special case you have to flag.

Spec updates: I wanted to compare this to the spec but it looks like [the relevant section of the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/develop/systems-architecture.md#opening-the-application-layer-authenticated-channel) is pretty out of date. Could you make an issue in the spec to change that to describe this updated use of an AEAD scheme? I flagged a detail or two inline that should definitely be included in the spec.

Some other clarification questions for me:
• I see some cloning of session keys. Can you explain what the best practice is for dropping these now that we have zeroize on drop? Should there be an explicit `drop` when things go out of scope or do we have confidence that the runtime will handle that?
• Where does the `Message` metadata live? It looks like it's totally separate from the `Message.content` in the proto file (that gets encrypted in the `To/From<Vec<u8>>` impl in the crypto module). Is that right? I remember a conversation with Jordan about the importance of not encrypting that metadata, and since the integration tests still work, that definitely isn't happening, but I don't follow the overall architecture.

2022-11-23 17:32 UTC, marsella commented on lock-keeper/src/crypto.rs
> +        Encrypted::encrypt(rng, &self.0, message, &AssociatedData::new())
thought: I'm guessing we'll want to add some meaningful associated data here. Can you make a note to make a decision about this in the spec issue?

2022-11-23 22:13 UTC, picklenerd commented
>  Where does the Message metadata live? It looks like it's totally separate from the Message.content in the proto file (that gets encrypted in the To/From<Vec<u8>> impl in the crypto module). Is that right? I remember a conversation with Jordan about the importance of not encrypting that metadata, and since the integration tests still work, that definitely isn't happening, but I don't follow the overall architecture.

The metadata that I added is actually in the return types of the public `LockKeeperClient` API. For things that go across the network, the metadata is encoded into the gRPC requests/responses using its built-in metadata capabilities. It basically works the same way as HTTP headers. Once the request/response makes it across the network, the metadata is pulled out and placed into the channel.

Metadata is only exchanged when the channel is opened, not when messages are passed across. Once the protocol is complete and the channel is closed, the metadata sent from the server is pulled out of the channel and placed into the result returned by `LockKeeperClient`.

2022-11-23 22:19 UTC, picklenerd commented on lock-keeper-key-server/src/server/session_key_cache.rs
> +                Ok(self.get_key(user_id.clone())?)
I believe this is a side effect of the hashmap's `entry` api which is used to remove the session entry if the key is expired. Our terrible and temporary key eviction strategy is to remove expired sessions when a user tries to use the expired session. @gatoWololo does that sound right?

This cache is being replaced with something permanent during the current development phase.

2022-11-23 22:20 UTC, picklenerd commented on lock-keeper/src/infrastructure/channel.rs
> +    rng: Arc<Mutex<StdRng>>,
I agree with the approach to keep it generic in the `lock-keeper` crate.

2022-11-24 00:18 UTC, gatoWololo commented on lock-keeper-key-server/src/server/session_key_cache.rs
> +                Ok(self.get_key(user_id.clone())?)
Yes, this is due to our use of the `Entry` API for `HashMap`. @marsella we _could_ take a reference and have the `get_key` function do the clone internally, but this allows the color to choose whether to clone or give up ownership of the `user_id` so it is a little more flexible, but less ergonomic.

We use the `Entry` API so we only have a single hashmap lookup in this function (`get_key`), we could do it without entry, but then we would need two lookups for deleting invalid keys.

2022-11-24 10:35 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +            _ => return Err(LockKeeperClientError::UnauthenticatedChannelNeeded),
done

2022-11-24 10:35 UTC, gijsvl commented on lock-keeper/src/crypto/generic.rs
> +    // #[cfg(test)]
removed instead of comment

2022-11-24 10:35 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +            _ => return Err(LockKeeperClientError::AuthenticatedChannelNeeded),
done

2022-11-24 10:37 UTC, gijsvl commented on lock-keeper/src/lib.rs
> +            }
I've just extracted the `TryFrom` part into a separate macro. I like that the calling macro is split into two separate macros to have a clear difference between authenticated and unauthenticated, I think it's less clear with that key word.

2022-11-24 10:38 UTC, gijsvl commented on lock-keeper-key-server/src/server/operation.rs
> +    async fn handle_authenticated_request(
Good call, I've removed the `handle_authenticated_request` in favor of one `handle_request` method. Should-be-authenticated messages over an unauthenticated channel would still fail because of the `ShouldBeAuthenticated` trait.

2022-11-24 10:43 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +            Some(session_key) => {
I was contemplating about this, but this is exactly regarding your point in your general comment:

> For the overall design, it sounds like the guarantee is, "if a channel has a session key and a given message should be authenticated, it will be authenticated." I was wondering if we can enforce something stronger: "if the channel has a session key, every message sent over it is authenticated."

By ignoring this check, it actually ensures that even a message doesn't necessarily needs to go over an authenticated channel will still go over the authenticated channel. If I add the error, it won't.

2022-11-24 10:48 UTC, gijsvl commented
@marsella about your general question:
> • I see some cloning of session keys. Can you explain what the best practice is for dropping these now that we have zeroize on drop? Should there be an explicit drop when things go out of scope or do we have confidence that the runtime will handle that?

An explicit drop is not necessary, objects will be dropped at the end of their scope anyway and will be zeroized in the process. The reason I've added some explicit drops at some points in the zeroize PR, is to just be very thorough and explicit about it sometimes.

2022-11-24 10:50 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +    pub(crate) session_key: OpaqueSessionKey,
Yes, this should have been read-only, I forgot to revert this change.

2022-11-24 10:52 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +        let mut channel_rng = StdRng::from_entropy();
yes, my bad

2022-11-24 10:53 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +        let context = AssociatedData::new().with_str("OPAQUE-derived Lock Keeper master key");
changed

2022-11-24 11:01 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +        message: T,
I've changed the encrypt function to take a `Message`, that's a good call. However, if I pass in `content` directly, I would basically get a `Encrypted<Vec<u8>>` and I think I like it better handling an `Encrypted<Message>`. But happy to change if you think that is better.

2022-11-24 11:02 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +        session_key: OpaqueSessionKey,
done

2022-11-24 11:03 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +                let result = match self.session_key.clone() {
done

2022-11-24 11:05 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +        self,
done

2022-11-24 11:05 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +        match self.session_key.clone() {
done

2022-11-24 11:07 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +    /// * rng - a reference to a secure random number generated.
done

2022-11-24 12:52 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +    /// can be converted to a `Message. In case a session_key is provided to the
done

2022-11-24 12:54 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +    /// AEAD scheme.
done

2022-11-24 14:10 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +    rng: Arc<Mutex<StdRng>>,
I've made this change in one commit: https://github.com/boltlabs-inc/key-mgmt/pull/373/commits/504995c763e1a27da472c00a504e2e5da9fedc67 I'm not sure if this is much better, I'm not sure how else to easily achieve this, but maybe one of you have a better idea?

2022-11-24 14:30 UTC, gijsvl commented on lock-keeper-client/src/api.rs
> +        };
Not sure if this is what you mean: https://github.com/boltlabs-inc/key-mgmt/pull/373/commits/ca0a2831d5d2f205f890819e19c3c81fda097370

2022-11-25 07:52 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +        Encrypted::encrypt(rng, &self.0, message, &AssociatedData::new())
https://github.com/boltlabs-inc/key-mgmt-spec/issues/147

2022-11-25 07:52 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +            arr[..32]
https://github.com/boltlabs-inc/key-mgmt-spec/issues/147

2022-11-28 15:52 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> +        }?;
```suggestion
        let server_response = match metadata.action() {
            ClientAction::Authenticate => client.authenticate(stream).await,
            ClientAction::Register => client.register(stream).await,

            // These actions generate an error because they should be on an authenticated channel
            ClientAction::CreateStorageKey
            | ClientAction::Export
            | ClientAction::ExportSigningKey
            | ClientAction::Generate
            | ClientAction::ImportSigningKey
            | ClientAction::RemoteGenerate
            | ClientAction::RemoteSignBytes
            | ClientAction::Retrieve
            | ClientAction::RetrieveAuditEvents
            | ClientAction::RetrieveSigningKey
            | ClientAction::RetrieveStorageKey => {
                return Err(LockKeeperClientError::AuthenticatedChannelNeeded)
            }
        }?;
```

2022-11-28 15:54 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> +            }
```suggestion
            ClientAction::Authenticate | ClientAction::Register => {
                return Err(LockKeeperClientError::UnauthenticatedChannelNeeded)
            }
```

2022-11-28 15:54 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> +            _ => return Err(LockKeeperClientError::AuthenticatedChannelNeeded),
Added a formatting suggestion to reduce duplication.

2022-11-28 18:52 UTC, picklenerd commented on lock-keeper/src/crypto/generic.rs
> +// #[cfg(test)]
This one can go too.

2022-11-28 19:12 UTC, picklenerd commented on lock-keeper/src/infrastructure/channel.rs
> +    rng: Arc<Mutex<StdRng>>,
This is gross but I'm not sure there's a better way to handle it aside from passing the RNG with every `send` and `receive`, which I definitely think is worse.

2022-11-28 19:48 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
I'm not a fan of this approach. The `Encrypted` wrapper is supposed to guarantee that the thing inside is encrypted. This allows us to easily produce unencrypted data that claims to be encrypted. This may not cause problems in the current code but I'm worried that this could cause problems in the future.

The code that creates an `Encrypted<Message>` should have its own implementation that explicitly states what it's doing and what it guarantees. I don't think it should use the existing macro or any `std` traits.

@marsella

2022-11-28 20:59 UTC, marsella commented on lock-keeper-client/src/api.rs
> +        };
I mean that the RNG is created on L88 and goes out of scope at L130 and I don't think this function ever spawns multiple threads that all have access to the same RNG. I thought we might not need the `Arc<Mutex<Rng>>` -- could just pass the `Rng` directly without having any issues with multiple threads accessing it simultaneously.

But it looks like the methods we call _do_ require the `Arc<Mutex<>>`.

2022-11-28 21:02 UTC, picklenerd commented on lock-keeper/src/infrastructure/channel.rs
> +        }
What situation does this protect against?

2022-11-28 21:02 UTC, marsella commented on lock-keeper-key-server/src/server/session_key_cache.rs
> +                Ok(self.get_key(user_id.clone())?)
Nah, this is fine. I was just wondering. Thanks!

2022-11-28 21:27 UTC, marsella commented on lock-keeper/src/crypto.rs
> +        message: T,
Oh yeah, that's a good call.

2022-11-28 21:32 UTC, marsella commented on lock-keeper/src/infrastructure/channel.rs
> +            Some(session_key) => {
Ah, right. That's nice. Can you add an inline comment here to that effect? Like 
```
// If the channel has a session key, _always_ encrypt a message sent over it!
```

2022-11-28 21:39 UTC, marsella commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
I think this is okay. We're reusing the AEAD encryption scheme we already implemented to do encryption under `SessionKey`s. 

E.g. we take a `Message`, encrypt it under a session key to get an `Encrypted<Message>`, and then send that blob over the network. So this impl is guaranteeing that once we encrypt a given message (e.g. that calls `impl_authenticated_message_conversion`), we can send that blob.

2022-11-28 21:43 UTC, marsella commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
Perhaps this could use a line of documentation to explain that context. Alternately / additionally, @picklenerd, do you think it would be better to have a wrapper type for `Message`s encrypted under a `SessionKey`, so it's more visually different from, say, an `Encrypted<StorageKey>` that's encrypted under the master key?

2022-11-29 00:40 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
This code allows a developer to take an unencrypted `Message` and turn it into an `Encrypted<Message>` for any `Message` whose JSON representation looks like: 

```json
{
    "ciphertext": [..bytes],
    "associated_data": [..bytes],
    "nonce": [..bytes],
}
```

So not an issue with the current code but definitely not misuse resistant.

I don't think we should use the `impl_message_conversion ` macro for this since it obscures the conversion process.

I don't think this should be a `From` or `TryFrom` either because it's too easy to use without knowing the context for converting. These could just as easily be doing the same JSON conversion and I doubt anyone would check before using it.

I think this should be a pair of methods on the `Encrypted<Message>` type that explicitly state what they do and what guarantees are made about the conversion. If we do the same conversion through JSON, we can at least document the methods and state this.

2022-11-29 01:13 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
This is one of the reason why I named the trait methods described in the ticket the way I did. The current macro hides what's happening a bit too much, especially when you can just `try_from()` and `try_into()` the `Message` type.

2022-11-29 08:52 UTC, gijsvl commented on lock-keeper-client/src/api.rs
> +        };
I think passing it on as an Arc<Mutex<>> as long as possible is the best approach, as soon as we lock it and translate it to an rng, we have to wait till it gets dropped for it to release. I've already encountered a deadlock now because of this, keeping the lock as short as possible is key. Which also means that the function that gets called within this scope ideally is as short as possible.

2022-11-29 09:18 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +        }
I wanted to avoid that we accidentally override a `session_key` that is used for a channel and as such transforming a channel into being reused for a different session. (technically, updating from non-authenticated to an authenticated channel is also reusing a channel for a different session, but with a very specific use-case)

2022-11-29 09:22 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +        }?;
woops, of course.

2022-11-29 09:22 UTC, gijsvl commented on lock-keeper-client/src/client.rs
> +            }
Done! Thanks!

2022-11-29 09:22 UTC, gijsvl commented on lock-keeper/src/crypto/generic.rs
> +// #[cfg(test)]
Removed

2022-11-29 09:22 UTC, gijsvl commented on lock-keeper/src/infrastructure/channel.rs
> +            Some(session_key) => {
Added!

2022-11-29 10:47 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +impl_message_conversion!(Encrypted<Message>);
I've created custom `try_from_message()` and `try_into_message()` methods on `Encrypted<Message>`

2022-11-29 15:39 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +                Vec::<u8>::from(self.associated_data.clone()).len() as u8,
`ciphertext` and `associated_data` don't have restricted lengths so we can't assume that the length fits in a byte. For example, the `remote_sign_bytes::RequestRemoteSign` message contains an arbitrary vector of bytes so this message can be any length.

2022-11-29 15:40 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +                Vec::<u8>::from(self.associated_data.clone()).len() as u8,
I think we could just add a `len` method to `AssociatedData` instead of cloning here.

2022-11-29 19:31 UTC, gatoWololo commented
Jordan has asked me to do a code review to get another set of eyes on this! I will have it in by today.

2022-12-01 09:15 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +                Vec::<u8>::from(self.associated_data.clone()).len() as u8,
I've moved it back to json representation, which is probably the safer bet. Unless you see any potentially better solution?

2022-12-01 09:15 UTC, gijsvl commented on lock-keeper/src/crypto.rs
> +                Vec::<u8>::from(self.associated_data.clone()).len() as u8,
same comment as above.

2022-12-01 15:17 UTC, picklenerd commented on lock-keeper/src/crypto.rs
> +                Vec::<u8>::from(self.associated_data.clone()).len() as u8,
I think this is a good solution for now since this is what we use for other encodings. We'll come up with a permanent encoding solution soon.

2022-12-01 16:58 UTC, picklenerd commented
I removed #260 from the list of tickets closed by this PR. We're going to leave it open for the derive macro.

2022-12-01 19:21 UTC, gatoWololo requested changes
It took a while to go through this hefty PR!

There has been a lot of churn, so it would be good to get this merged even if its now perfect. We think that's the best thing to do. So I have some minor feedback, we will leave #384 open and come back at a later time. I have some thoughts on a design iteration for authenticated channels. I will post these in #384 

I also don't like that our rng is locked behind a mutex shared by all concurrent operations. I know there is concerns about entropy, but I don't think using a Mutex is the right solution for this. @marsella we should have a conversation about this when you get back!

I have some minor feedback for now.

2022-12-01 19:21 UTC, gatoWololo commented on lock-keeper-client/src/api/authenticate.rs
> +        channel: &mut ClientChannel<StdRng>,
The fact our `ClientChannel` and `ServerChannel` have a `StdRng` is an implementation detail, we should not have to think about this when using them.

We should change the `rng` field in `Channel` definition to something like:
```rust
rng: Arc<Mutex<dyn CryptoRng + RngCore>>,
```
(I think the Mutex takes care of the boxing so we don't need a `Box` around the dynamic trait). This way we don't need the type parameter `G` and all our `ClientChannel`s or `ServerChannel`s.

Otherwise we might just be able to change it in the type aliases to be:
```rust
pub type ServerChannel = Channel<Result<Message, Status>, RequestMetadata, StdRng>;
pub type ClientChannel = Channel<Message, ResponseMetadata, StdRng>;
```
This might be cleaner?

2022-12-01 19:47 UTC, picklenerd commented on lock-keeper-client/src/api/authenticate.rs
> +        channel: &mut ClientChannel<StdRng>,
I like the `dyn` trait in the `rng` field if that compiles.

2022-12-05 10:01 UTC, gijsvl commented on lock-keeper-client/src/api/authenticate.rs
> +        channel: &mut ClientChannel<StdRng>,
I tried that at first, but it didn't compile that easily. So, first I get this error:
<img width="1629" alt="Screenshot 2022-12-05 at 10 58 00" src="https://user-images.githubusercontent.com/11486413/205608446-e895f500-ed0b-4fc2-a805-6f607144cdbc.png">
I've tried to use the compiler's suggestion, but it also gets very messy because it needs to match the rng that we pass in. Basically, we would have to change the rng everywhere to this "NewTrait". 

I might be missing something here and I'm open to suggestions...

2022-12-05 16:59 UTC, gatoWololo commented on lock-keeper-client/src/api/authenticate.rs
> +        channel: &mut ClientChannel<StdRng>,
Gotcha. I didn't realize Rust didn't allow this! @picklenerd do you have a reason you don't like defining `ClientChannel` as so:
```rust
pub type ClientChannel = Channel<Message, ResponseMetadata, StdRng>;
```

2022-12-05 19:35 UTC, gatoWololo approved these changes

2022-12-06 14:09 UTC, marsella approved these changes
Sorry, looks like my review is blocking this. LGTM.

2022-12-06 15:11 UTC, merged