Refactor Channel types #260
boltlabs-inc/key-mgmt pull request #394
Opened 2022-12-06 19:12 UTC by picklenerd

Closes #260

2022-12-07 16:49 UTC, picklenerd commented
I have a cleanup commit with some documentation updates and some minor changes to the channel params in the client handlers. I'll push it as soon as I'm on an internet connection that allows me to.

2022-12-08 01:31 UTC, gatoWololo requested changes
Looks good! It is very satisfying seeing all the macros go away. Lots of files were touched, but mostly to clean them up :)

I had two high level thoughts. Should we create an issue for the `Arc<Mutex<Rng>`? I'm still not sure about that and would like to have a dicussion on it to make sure we are doing the right thing. 

I see we are cloning the session_key as needed. Are we worried about having a few copies of the session_key around? I know those are sensitive so it seems weird to have a couple of copies around.

2022-12-08 15:20 UTC, picklenerd commented on lock-keeper-client/src/api/generate_secret.rs
> +        mut channel: ClientChannel<Authenticated<StdRng>>,
I think this is a place where it needs to be generic since `Authenticated` is defined in the `lock-keeper` crate. Maybe we could do a type alias in the `lock-keeper` crate instead?

@marsella What do you think?

2022-12-08 15:22 UTC, picklenerd commented on lock-keeper/src/types/operations/get_user_id.rs
> +    /// return encrypted storage key
No it is not!

2022-12-08 15:28 UTC, picklenerd commented on lock-keeper/src/types/operations.rs
> +impl<T: for<'a> Deserialize<'a> + Serialize> ConvertMessage for T {}
Added a blurb.

2022-12-08 15:29 UTC, picklenerd commented on lock-keeper/src/infrastructure/channel.rs
I think you marked the wrong line, but I added comments to the two `AUTH` types.

2022-12-08 15:30 UTC, picklenerd commented on lock-keeper-client/src/api/generate_secret.rs
> +        mut channel: ClientChannel<Authenticated<StdRng>>,
I think the generic is probably better here since a shared type alias will end up being used over the generic option and we'll lose the genericness of the `lock-keeper` crate.

2022-12-08 20:20 UTC, picklenerd commented
> I had two high level thoughts. Should we create an issue for the Arc<Mutex<Rng>? I'm still not sure about that and would like to have a dicussion on it to make sure we are doing the right thing.

Yeah I don't think that's related to this PR so it would be nice to have a separate issue.

2022-12-08 20:29 UTC, picklenerd commented
> I see we are cloning the session_key as needed. Are we worried about having a few copies of the session_key around? I know those are sensitive so it seems weird to have a couple of copies around.

We could change the channel to hold an `Arc` instead of an owned copy but I don't think that solves any security problem. You can still clone the key inside whenever you want. I think that's actually worse since right now you know when it's going to be dropped. With an `Arc` it can pretty much live forever any time someone clones the `Arc`.

I think there are a few places where the clones aren't necessary though. I'll go through and remove the ones that I can.

2022-12-08 20:37 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> -#[derive(Debug, ZeroizeOnDrop)]
The fields that need to be zeroized get dropped already implement `ZeroizeOnDrop`. They'll still be zeroized when this is dropped. Putting this trait on struct types makes it impossible to move values out of the struct which forces unnecessary cloning.

2022-12-08 20:38 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> -#[derive(Zeroize, ZeroizeOnDrop)]
See other comment on `LockKeeperClient`.

2022-12-08 20:40 UTC, picklenerd commented on lock-keeper-client/src/client.rs
> -                auth_result.zeroize();
This type no longer implements `ZeroizeOnDrop` but the fields that need to be zeroized still do. The function returns after this line and drops the `auth_result` so they will basically still be dropped at the same time.

2022-12-09 21:33 UTC, marsella commented on lock-keeper-client/src/api/generate_secret.rs
> +        mut channel: ClientChannel<Authenticated<StdRng>>,
I mean, we were trying to maintain the lock-keeper = generic boundary, but it might be okay to revisit that. I want to keep the cryptography code generic for sure but this is sort of directly client code (that just happens to live in lock-keeper), so if we make a choice for the client it might be okay to hard-code it here.

This is a bigger abstraction question though, so for the purpose of this PR I'd rather keep it generic.

2022-12-09 22:36 UTC, picklenerd commented
We had a bug in CI where it wasn't returning an error code during test failures. This PR was actually broken thanks to the `get_user_id` operation. I'm working on a fix.

2022-12-09 22:41 UTC, picklenerd commented
The fix for this is kind of ugly so I'm going to leave this open for re-review.  I left it as a separate commit for now.

2022-12-13 00:05 UTC, merged