Add policy engine API
boltlabs-inc/key-mgmt pull request #46
Opened 2022-06-28 20:00 UTC by marsella

This PR creates a `PolicyEngine` trait that the key server will interact with. The design intention here is that we will instantiate this trait for the mighty block policy engine, a dummy policy engine for us to test with, and eventually our own policy engine implementation.

I tried to document assumptions and sketch out the basic types this will return. I didn't explicitly make them `Serialize` / `Deserialize` because I don't want to require the external policy engine to create these specific types  -- it's fine if the (internal) trait instantiation takes the types returned from the external engine, vets / validates them, and instantiates the specific return types this API requires.

Fixes #14

2022-06-29 09:19 UTC, indomitableSwan requested changes
1. We need to specify the _policy configuration_ for the policy engine:
- is this part of system setup config file?
- who are the asset fiduciaries? what information do we need about them? 
- a placeholder for signature scheme.

Relevant excerpt from draft specification:

> System setup determines the defaults for creation and use of digital asset keys.
> 
> Digital Asset keys require a policy configuration determined by the Service Provider at system setup.  This policy configuration captures the systemwide default set of asset fiduciaries for a key with shared control and can be extended to support key-specific defaults.
> 
> [MVP] A default policy configuration file determined and authenticated at system setup. This file includes:
> 
> A `control_flag` indicator. If set to `True` unilateral control keys are allowed in the system. If set to `False`, unilateral control keys are not allowed in the system.
> 
> The maximum number of each type of key that an end customer may create. The default  in the MVP is set to two: one self-custodial key with shared control and one delegated-key with shared control.
> 
> An access control structure that specifies the default set of asset fiduciaries for a key with shared control. This access control structure is stored internally on the key servers and used for final approval/rejection of key use operations and for auditing/logging purposes.  

If there is a problem with the draft specification here, we should update as needed in parallel with this PR.

2. Do we already have an epic to capture authentication and session-handling with the policy engine? Can we add some TODOs and a link to the relevant epic here?

2022-06-29 09:19 UTC, indomitableSwan commented on src/policy_engine.rs
> +/// to one of the specified fiduciaries.
Won't we enforce this via validation of a `TransactionApprovalDecision`? It appears that we are missing some machinery to spell this out, i.e., we need a policy configuration file that specifies the system's asset fiduciaries.

2022-06-29 20:38 UTC, marsella commented on src/policy_engine.rs
> +    Reject(RejectionContext),
Oh, I see what you mean. I was thinking the `PolicyEngine` would collect them but actually it seems fine to just make this a vector of rejection contexts and require that it's not empty. There might be a better way to specify this enum since we have some constraints on the lengths of the vectors, but I'll just document those constraints for now.

2022-06-29 21:31 UTC, marsella commented on src/policy_engine.rs
> +/// signatures or a note to describe the rejection.
Oh, oops. I already did this!!

2022-06-29 21:37 UTC, marsella commented on src/policy_engine.rs
> +/// to one of the specified fiduciaries.
I used "assumption" but I think that's the wrong word. This won't be enforced by `TransactionApprovalDecision`. This will be a property of the `ApprovalSignature` type - you can only create one if you give it a policy config with the asset fiduciaries specified and a signature, and the signature matches one of fiduciaries. The `TAD` will enforce that there is (at least?) one signature per fiduciary.

2022-06-29 21:50 UTC, marsella commented
> @marsella I have made the module as well as the components public in order for this to be included in the docs. Could you verify this is actually as expected, or do we want some stuff to be private? In which case we have to make sure the docs still build.

Good question. I made it private because I was thinking it would be a submodule in the key server crate, and because this doesn't actually need to be public facing -- in that, we are going to implement the trait for any external policy engine instantiations that come along. However, since we expect external policy engines to have APIs that basically satisfy this outline, it also seems fine to have it public.

2022-06-30 12:24 UTC, indomitableSwan requested changes
Some philosophical comments around naming and an outstanding task that should be captured as an issue in https://github.com/boltlabs-inc/key-mgmt-spec.

2022-06-30 12:24 UTC, indomitableSwan commented on src/policy_engine.rs
> +/// from all fiduciaries.
I've been muddling terms a bit, I think, between CS and maths. We are really talking about _access structures_ (and here we are specifying an (n,n)-threshold access structure, technically). 

Here we might say: 

`The policy engine relies on a fixed set of asset fiduciaries; this set is specified in the policy configuration. When a key operation is requested, the Policy Engine asks each asset fiduciary for a corresponding approval decision. Final approval of the operation by the Policy Engine requires receipt of an approval from each asset fiduciary specified in the policy configuration.`

2022-06-30 17:18 UTC, marsella commented on src/policy_engine.rs
> +pub struct ApprovalSignature;
That's a good call, I'll fix.

2022-06-30 17:25 UTC, marsella commented on src/policy_engine.rs
> +    /// signature per asset fiduciary.
I added notes about this to that issue. Is this a spec-before-code situation? Should I make a PR in the spec describing these intentions?

2022-06-30 17:27 UTC, marsella commented on src/policy_engine.rs
> +    /// The set of asset fiduciaries.
I'll add it here and also in the top level doc for this config -- I think all of these config options are system-wide.

2022-06-30 17:52 UTC, indomitableSwan commented on src/policy_engine.rs
> +/// Configuration for an asset fiduciary.
Yep, misread it.

2022-06-30 17:53 UTC, indomitableSwan commented on src/policy_engine.rs
> +    /// signature per asset fiduciary.
Yes, that would be great.

2022-06-30 17:55 UTC, indomitableSwan reviewed
Other than adding an issue to key-mgmt-spec, this is ready for merge. (I think you mentioned creating a PR, but I'd also be fine with an issue.)

2022-06-30 18:48 UTC, indomitableSwan approved these changes

2022-06-30 21:13 UTC, merged