Add additional methods/types for general use of crypto module.
boltlabs-inc/key-mgmt pull request #525
Opened 2023-06-09 23:25 UTC by gatoWololo

Closes #524 and #496

See those issues for the list of changes this adds.

@marsella I had a few questions about these changes: I tried to leave the existing crypto code intact, and instead add new types and methods. I'm unsure if this is the right approach and instead I could merge some types together more. I will mark these as comments on the PR.

I'm happy to change the code as needed to meet your cryptography standards :bow:

2023-06-09 23:26 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +    /// message using ??? TODO.
I could use some help: What hash is used by the `verify` method here?

2023-06-09 23:29 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +pub struct SigningPrivateKey(ecdsa::SigningKey);
I created a separate `SigningPrivateKey` type here, totally separate from the existing `SigningKeyPair`. We can change our `SigningKeyPair` to use this new type. E.g:
```diff
pub struct SigningKeyPair {
-    signing_key: ecdsa::SigningKey,
+    signing_key: SigningPrivateKey
}
```
This would allow us to merge some of the functions while still allowing both `SigningPrivateKey` and `SigningKeyPair` to be used independently.

2023-06-09 23:30 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +    }
It is unclear to me from the docs what format, if any, these function use for the serialized representation.

2023-06-09 23:32 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +    pub fn sign_prehash_recoverable(
We could fold these methods into our `Signable` trait if we wanted.  There is a bit of duplication since we have multiple variants of this function: sign, sign_prehash, sign_recoverable, sign_prehash. Not sure if there is a way to minimize this.

2023-06-09 23:33 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +pub struct SigningPrivateKey(ecdsa::SigningKey);
Our other products have code written which expect a stand-alone signing private key, that's why I created this separate type instead of using our existing `SigningKeyPair`. Also `SigningKeyPair` expects `AssociatedContext` which I wasn't sure what to give it.

2023-06-09 23:51 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +pub struct SigningPublicKey(pub VerifyingKey);
This was just moved down from higher in the file.

2023-06-09 23:53 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
>  };
This file has gotten really big. I avoided moving types around to make the PR easier to understand. But we may wanna break the file down.

2023-06-13 17:33 UTC, marsella requested changes
Thanks Omar, this looks pretty good. The mechanics of this look pretty good, I have a few important documentation-related comments that I think we need for the contexts in which this'll be used. It would also be helpful to chat about the structure of this for a few minutes.

2023-06-13 17:33 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +    /// message using ??? TODO.
Yikes, this is really hard to track down. The verify method is parameterized by the type of the signature; the signature should have an associated type called `Digest` that'll implement a hash function. All the verify methods are generic over the hash. 
The signature type we use is `ecdsa::Signature`, which is a type alias for `ecdsa_core::Signature<Secp256k1>`. I poked around a bit and I think that it uses `sha2-256` for the hash function -- [see this instantiation](https://docs.rs/k256/0.11.0/src/k256/ecdsa.rs.html#92-96) of `DigestPrimitive` for the `Secp256k1` curve.

2023-06-13 17:33 UTC, marsella commented on lock-keeper/src/crypto/signing_private_key.rs
> +    }
question: Are these methods used somewhere? I don't love giving direct access to these; it's not really a security issue but, like, the whole purpose of a signature is to verify it, and since we provide functions to do that, it would be ideal to restrict access to these internal types.

2023-06-13 17:33 UTC, marsella commented on lock-keeper/src/crypto/signing_private_key.rs
> +pub struct SigningPrivateKey(ecdsa::SigningKey);
Implementing `SigningKeyPair` in terms of your `SigningPrivateKey` seems fine to me. The associated context for the key pair was (in the old protocol) intended to be all the versioning and context info that we would want to validate when we pulled + decrypted one of our keys out of storage. I don't know the maestro protocol well enough to understand if we're maintaining state like that, but it's fine to use this separate type for the Maestro use case.

2023-06-14 17:53 UTC, marsella commented
Also, general request for you: could you please wait to squash your commits until we are done with the review cycle? I know it makes rebasing more annoying, but it's going to be much easier for me to re-review if I can see incremental changes via the commit history.

2023-06-15 00:02 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +    }
Cool. Makes sense.

2023-06-15 01:18 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +    /// message using ??? TODO.
Thanks! This was really helpful.

2023-06-15 01:18 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_private_key.rs
> +    pub fn sign_prehash_recoverable(
For the sake of simplicity, I will not do this.

2023-06-15 20:19 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +    /// to be an already hashed message.
I ended up not doing this since I got rid of all the `.*pre_hash.*` methods. Let me know if this works :)

2023-06-15 20:32 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq)]
Like we have talked about in the zeroize tickets, only the underlying type `SigningPrivateKey` implements `ZeroizeOnDrop` so this type no longer needs it.

2023-06-16 21:20 UTC, marsella commented on lock-keeper/src/crypto/signing_private_key.rs
> +    /// message using SHA3 keccak256.
nit: the standard is SHA3-256; the algorithm selected by the standard is the Keccak family of hash functions. It might be slightly more standard to write this (here and below) like "SHA3-256 (Keccak)"

2023-06-16 21:20 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +    /// to be an already hashed message.
I think that's okay for now. What's the revealed module structure of this library, though? It would be nice to add some high-level documentation _somewhere_ to be explicit that this is a low-level cryptographic library and it does not do any validation or verification of messages; that must be handled by the calling application.

2023-06-16 21:27 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +    /// to be an already hashed message.
This is kind of awkward because this module is intended to be resuable, but the `lock_keeper::crypto` module also includes a bunch of application-specific stuff for the old protocol.

It would be nice if we could bundle the bits we use externally in a separate module or something so it was clear which parts are "use this to consolidate our cryptography" and which are "outdated crypto for a protocol you're not using".

2023-06-20 12:52 UTC, marsella commented on lock-keeper/src/crypto/signing_private_key.rs
> +    }
suggestion: we had talked about consolidating these into a single `into_parts` method.

2023-06-20 22:44 UTC, gatoWololo commented on lock-keeper/src/crypto/signing_key.rs
> +    /// to be an already hashed message.
I agree, I tried really hard not to move things around for the sake of not bloating this PR. I made a separate issue to address this. See #526 and lmk if I should add anything else to that new issue.

2023-06-21 18:27 UTC, marsella commented on lock-keeper/src/crypto/signing_key.rs
> +    /// to be an already hashed message.
Yep, that was a good call. Thanks for writing up the issue.

2023-06-21 18:29 UTC, marsella approved these changes
Looks good, thanks!

2023-06-21 22:49 UTC, merged