WIP Sharding Code
boltlabs-inc/key-mgmt pull request #536
Opened 2023-07-20 00:25 UTC by gatoWololo

@marsella If you could give me some initial feedback that would be great!

2023-07-20 00:33 UTC, gatoWololo commented on lock-keeper/src/crypto/shard.rs
> +            .collect();
When you shard a value, the shards have an additional byte at the front representing the ID of the shard. This makes the size of the shards 16 (original shard size) + 1 (ID byte). So have to strip this value when chunking + encrypting, and later add this value back when rebuilding the key.

Which seems pretty ugly. Ideally, we would remove this code and work with 17 bytes shards? Thoughts?

2023-07-20 14:54 UTC, marsella requested changes
Thanks for tagging me on this, Omar! The root of the complications you've pointed out here are because we are using the wrong AES library; the one included here provides a low-level interface for cryptographers. There's a better library (linked in comments) that provides a high-level interface for applications. We need to use that one instead.

2023-07-20 14:54 UTC, marsella commented on lock-keeper/Cargo.toml
> +aes = "0.8"
This [`aes`](https://crates.io/crates/aes) crate is not the correct choice for the dependency. Per the crate documentation:
> This crate implements the low-level AES block function, and is intended for use for implementing higher-level constructions only. It is NOT intended for direct use in applications. 

We should be using the [`aes-gcm`](https://docs.rs/aes-gcm/latest/aes_gcm/) crate instead, which depends on `aes` but provides a much better user interface and has been audited. It also supports `no_std` and can avoid allocation if that is necessary for our use case.

2023-07-20 14:54 UTC, marsella commented on lock-keeper/src/crypto/shard.rs
> +            .collect();
Yeah, thanks for flagging this. When we switch to the aes-gcm library, we can circumvent the low-level break-your-message-into-chunks interface altogether and encrypt arbitrary-sized messages, so this should go away.

2023-07-20 14:54 UTC, marsella commented on lock-keeper/src/crypto/shard/chunk.rs
> +pub fn get_cipher(seal_key: &[u8]) -> Aes256 {
Perhaps you plan to do this in the future, but the seal key would ideally have its own type so it's easier to identify.

2023-07-20 14:54 UTC, marsella commented on lock-keeper/src/crypto/shard/chunk.rs
> +        get_cipher(seal_key).encrypt_block(block);
Noting: this library encrypts in-place; you can use the corresponding [`encrypt_in_place` methods](https://docs.rs/aes-gcm/latest/aes_gcm/index.html#in-place-usage-eliminates-alloc-requirement) in the `aes-gcm` library if that's an important feature.

That might be affecting some of the zeroizing behavior that you noted was missing; it might not be possible to zeroize the original input if we use these in-place encryption methods. From a cryptographic perspective I would be fine to allocate memory and explicitly zeroize the original input.

2023-07-26 01:19 UTC, gatoWololo commented
@marsella This is now ready for a review!

2023-07-26 01:19 UTC, gatoWololo commented on lock-keeper/src/crypto/generic.rs
>  pub enum CryptoError {
Moved around some of the variants to be in alphabetical order.

2023-07-26 01:20 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +/// TODO What exactly is a seal key?
I should ask someone what a seal key actually is, so we can document it.

2023-07-26 01:21 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +        let result = cipher.encrypt(&nonce, self.material.as_slice());
I ended up NOT encrypting in place, I think this makes it easier to reason about copies and I can explicitly zeroize.

2023-07-26 01:21 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +// TODO: Should encrypted shards or nonce be zeroized after use?
This is a question for you :)

2023-07-26 17:48 UTC, marsella requested changes
Thanks, this looks pretty good! I have some cleanup notes and other thoughts throughout.

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +pub fn rebuild_key_from_encrypted_shards(
question: Why is this and `rebuild_key_from_shards` not methods on `SigningPrivateKey`?

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +    /// Convert key into a format that `[aes_gcm]` understands.
todo: Make this actually be a link to the `aes_gcm` library, or the output type.

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +            .map_err(|_| CryptoError::IncorrectSealKeySize(length))?;
question: Will this fail in both the too-long and too-short cases, or only too-short?

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +    pub fn get_shards(&self) -> &[EncryptedShard] {
todo: I would recommend removing `get_` from these names to align with [Rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter). Is that an annoying API change?

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +    pub fn take_shards(self) -> Vec<EncryptedShard> {
nit: Similarly, I would call this `into_shards`

2023-07-26 17:48 UTC, marsella commented on lock-keeper/src/crypto/sharding.rs
> +    fn encrypt_shard_works() {
thought: This is a kind of nebulous thing to test if we're not also decrypting it. You might check, say, that the encrypted shard is different from the unencrypted one, but the property we really want to test ("an attacker cannot determine any information about the plaintext from the ciphertext") is not exactly falsifiable.

2023-07-27 20:52 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +// The number of shards we want to use must be a constant
Oh neat!

2023-07-27 20:58 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +#[derive(Debug, Clone, Eq, PartialEq)]
That's a great idea. I can implement by own Debug instances.

2023-07-27 21:15 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +    material: [u8; SEAL_KEY_LENGTH],
I tried adding the Box but it causes issues since the new constructor is a const function right now:
```rust
pub const fn new(seal_key: [u8; SEAL_KEY_LENGTH]) -> Self
```
This makes it possible to use the constructor to create const `SealKey` values for testing in this code and in the enclave:
```rust
const TESTING_SEAL_KEY: SealKey = SealKey::new([
        249, 95, 53, 174, 82, 104, 71, 122, 147, 115, 101, 210, 113, 233, 22, 31, 46, 191, 19, 167,
        45, 199, 77, 215, 193, 41, 153, 197, 10, 193, 255, 145,
    ]);
```
I can't do that with the Box. I did add a `ZeroizeOnDrop` to this type! I don't think this is an issue memory management-wise. This type is slightly large at 32-bytes but I think that's still reasonable.

2023-07-27 21:20 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +    if bool::from(non_zero_scalar.is_none()) {
Thanks! We weren't sure how to do this :dizzy_face:

2023-07-27 22:16 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +        // Note: Cannot use `assert_eq!` as `UnencryptedShard` does not impl Debug.
Great idea!

2023-07-27 22:19 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +pub fn rebuild_key_from_encrypted_shards(
Good point.

2023-07-27 22:20 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +            .map_err(|_| CryptoError::IncorrectSealKeySize(length))?;
It will fail both if the vec is both too short or too long.

2023-07-27 22:25 UTC, gatoWololo commented on lock-keeper/src/crypto/sharding.rs
> +    fn encrypt_shard_works() {
That makes sense. _deleted_

2023-07-27 22:36 UTC, gatoWololo commented
@marsella This is ready for re-review! I marked all the conversations as "Resolved" for things I fixed/changed. I commented on the few that remain.

2023-07-28 14:09 UTC, marsella approved these changes
Looks good, thanks!

2023-07-28 17:32 UTC, merged