83 opaque password encryption
boltlabs-inc/key-mgmt pull request #537
Opened 2023-07-20 13:33 UTC by tposavec

Closes #530 

This is the lock-keeper portion of the encrypted OPAQUE password task.

NOTE: the branch name is confusing/wrong because it was created before we broke up the task in two tickets.

The branch for this PR should have been named 530-opaque-password-encryption.

NOTE: For reference, there is an older PR https://github.com/boltlabs-inc/key-mgmt/pull/531 that was closed because the code had to be refactored.

2023-07-20 19:35 UTC, gatoWololo requested changes
Overall the code looks good! Left some comments about style and small changes. I left more comments than I usually would about style since you are still getting used to how we write code :)

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ZeroizeOnDrop)]
I think we talked abount not implementing `Debug` for password to avoid it accidentally being printed.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +    #[instrument(skip_all)]
Ooh, I didn't realize we could use the instrument macro inside trait impl blocks like this!

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +    #[instrument(skip_all)]
I think you wanna add `err(Debug)` like this: `#[instrument(skip_all, err(Debug))]` for this. This makes the error logging a little nicer.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +        Ok(Self {
Personally, I like avoiding unnecessary comments like this one. This comment is mostly stating the obvious. Our code mostly follows this style. I do appreciate all the other comments throughout!

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +    /// Encrypt a `Password` using the provided encryption key.
When referring to types that are in scope in doc strings. You can use the syntax [`Password`] to have Rust create a hyperlink in the generated docs. I think you should switch this one here. As well as  `EncryptedPassword` and `CryptoError` below

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            .map_err(|_| CryptoError::EncryptionFailed)?;
In this `map_err` you probably wanna print the error via our error log:
```rust
 .map_err(|e| {
     error!("{:?}", e);
     CryptoError::EncryptionFailed
     })?;
```
Otherwise we know that encryption failed, but we don't know why it failed. This will make it easier to debug if it ever happens.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +    key_server_name: Vec<u8>,
How come key server name is a `Vec<u8>` instead of a String? I see below that it seems to be in hex format?

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +impl TryFrom<Vec<u8>> for PasswordContext {
This conversion seems to be infallible. You can just use the `From` trait in that case. This simplifies the code since we don't have to handle a non-existent error path.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
Should this implement `Debug`?

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +impl std::fmt::Display for EncryptedPassword {
I'm curious what the use case for the `Display` implementations are? We don't really use them in any of our repos and I haven't found it necessary.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +    key_server_name: Vec<u8>,
If there isn't really a use case for using `Vec<u8>` over string. I would suggest using strings as they seem a better fit for this use case.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            context: PasswordContext {
You can use your constructor here to simplify:
```rust
context: PasswordContext::new(KEY_SERVER_NAME),
```

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            context: PasswordContext {
Same as above, simplify `PasswordContext` creation here.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +
I don't think we have solid guidelines about whitespace. But personally, I think we could get rid of some of these newlines. It makes the code a little more compact. I like new lines between logically distinct lines of code. But here they can be compressed a bit.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +
Similar comment about these new lines here.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +
Last example I will point out about newlines I consider unnecessary.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            context: PasswordContext {
Simplify `PasswordContext` construction.

2023-07-20 19:35 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            context: PasswordContext {
lol

2023-07-20 19:40 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            .extend_from_slice("__baaaaaad__".as_bytes());
Lol

2023-07-20 20:45 UTC, marsella requested changes
Thanks for the updated PR! Looks much better already. Apologies in advance -- I think I have some overlapping comments with Omar.

Can you explain the `pub(super)`s her? I think some of these types should just be straight-up public; in the previous use case, this module was only used by types within the library, but now it's going to be used by external libraries and the primary types (`Password`, `PasswordKey`) likely need to be public. You might have to fight a little with the existing module publicity to make sure those are exposed.

In general for testing, I don't include explicit `println` s unless I'm actively debugging something. Once the test works, if I think there needs to be additional info, I either add context to the asserts to give a hint as to what went wrong in a failure case or use the `tracing` logging infrastructure. I don't think this crate is actually set up with tracing though. This is a stylistic preference and I'll defer to @gatowololo if he disagrees or doesn't care.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +    fn context(&self) -> &PasswordContext {
Do you expect to use this method in this crate in a later refactor? If not, I'd recommend removing it. If it's supposed to be publicly accessible, update the publicity and remove the `#[allow(...)]`.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +/// A password contains password `material` and `context` data.
suggestion: I think this would benefit from more specific context about how you expect the password type to be used and what guarantees this type provides.

In particular, this isn't a normal user facing password in our application, and this type isn't really appropriate for that use case: it doesn't check any measure of "strength" or security of the password. Will send you some private notes about our actual application.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +impl Password {
todo: I don't see any constructor other than the `TryFrom<Vec<u8>>`, which is only appropriate for serialized passwords.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +    fn new<T: AsRef<[u8]>>(key_server_name: T) -> Self {
todo: This function seems like it's supposed to be public. I would recommend changing the publicity and removing the allow if so.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +        };
todo: Same note as above re: removing clone for the context.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +#[derive(Debug, Clone, PartialEq, Eq, Zeroize, ZeroizeOnDrop)]
issue: As above, I'm inclined to prefer a redacted `Debug` implementation and no `Display` implementation because I don't want this secret getting left around.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +    /// Generate a new symmetric AEAD encryption key from scratch.
todo: Instead of "from scratch" I would say:
```rust
/// Generate a new `PasswordKey` uniformly at random.
///
/// A `PasswordKey` is a 32-byte pseudorandom key for use in the 
/// [ChaCha20Poly1305 scheme](https://www.rfc-editor.org/rfc/rfc8439) for
/// authenticated encryption with associated data (AEAD).

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +/// An encrypted password contains `ciphertext`, `context` and `nonce`.
todo: would recommend docs like

```rust

/// A ciphertext representing a `Password`, encrypted under the
/// [ChaCha20Poly1305 scheme](https://www.rfc-editor.org/rfc/rfc8439) for
/// authenticated encryption with associated data (AEAD).
///
/// As implied by the scheme name, this uses the recommended 20 rounds and a
/// standard 96-bit nonce. For more details, see the
/// [ChaCha20Poly1305 crate](https://docs.rs/chacha20poly1305/latest/chacha20poly1305/index.html).

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +        Self::from_bytes(&bytes)
todo: Zeroize `bytes` before returning from this method.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +    fn from_bytes(key_material: &[u8]) -> Result<Self, CryptoError> {
thought: I wish chacha20 keys had a more standardized format than just being a random byte string :(

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +}
issue: I would rather delete this function and add key derivation to this module when we need it. Is that a functionality currently happening elsewhere in our code base?

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +        // len || key || context
nit: comment is out of date; there's no context for a `PasswordKey`.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +        if len != 32 {
nit: use your constant here instead of the raw number 32

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +            .into();
question: Can you use parsebytes here to avoid the offset code? I hated writing that originally.

2023-07-20 20:45 UTC, marsella commented on lock-keeper/src/crypto/password_key.rs
> +    fn password_key_from_bytes_wrong_length_fails() -> Result<(), CryptoError> {
todo: I think this test should try both the too-long and too-short cases.

2023-07-20 21:38 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +        let password_material = parse.take_bytes(password_length as usize)?.to_vec();
Password length is being "extended" from a `u16` to a `usize` this conversion is always valid and guaranteed to never truncate data (unlike converting from usize -> u16 which can truncate data :grimacing: , I consider this a flaw in Rust). But we should add a comment here to be explicit.

2023-07-20 21:46 UTC, gatoWololo commented on lock-keeper/src/crypto/password.rs
> +            context: self.context.clone(),
In this case you do actually need the clone:
```rust
error[E0509]: cannot move out of type `password::Password`, which implements the `Drop` trait
   --> lock-keeper/src/crypto/password.rs:158:22
    |
158 |             context: self.context,
    |                      ^^^^^^^^^^^^
    |                      |
    |                      cannot move out of here
    |                      move occurs because `self.context` has type `PasswordContext`, which does not implement the `Copy` trait

```
This is because `Password` implements `ZeroizeOnDrop` so the compiler won't let you move a field out of the struct. Even though this field is never used in the `Drop` impl, the compiler is unable to reason about this.

This is an issue with using `ZeroizeOnDrop`. One workaround if we really wanted to avoid the clone is to create a `InnerPassword` type which just wraps the `Vec<u8>` this way the entire `Password` struct does not need to impl drop. This the reason I propose the approach described in https://github.com/boltlabs-inc/tss-ecdsa/issues/330

2023-07-20 21:52 UTC, gatoWololo commented
> I don't think this crate is actually set up with tracing though. This is a stylistic preference and I'll defer to @gatoWololo if he disagrees or doesn't care.

I agree with your stylistic preference and we also don't usually use `println!`. We rely on asserts which can take [an optional message](https://doc.rust-lang.org/std/macro.assert.html#custom-messages)!

The entire crate does have support for tracing, but I don't think we use it in the crypto module. The problem with using `tracing` in tests is that you have to init the logger per thread, which is annoying! So I would not advise to do that.

2023-07-21 12:35 UTC, marsella commented on lock-keeper/src/crypto/password.rs
> +#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
I am less concerned about logging encrypted blobs, although it might be best to manually redact the nonce.

2023-07-28 22:28 UTC, tposavec commented
I did a major refactor of this PR. I'm closing it, and creating a new PR.

2023-07-28 22:28 UTC, closed without merging