549 add serialization trait for decryptor type
boltlabs-inc/key-mgmt pull request #550
Opened 2023-08-16 17:14 UTC by tposavec

Closes #549

2023-08-16 19:28 UTC, gatoWololo reviewed
Looks good to me. I will defer to Marcella for the crypto details.

2023-08-16 19:29 UTC, marsella requested changes
Thanks! I have a few comments about ways to simplify and reduce cloning throughout.

Are the changes to the `Password` type supposed to be here? They don't seem related to the issue description.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +        let nonce: Vec<u8> = decryptor.nonce.to_vec();
todo: Rather than cloning each field, I would destruct (?) this like so:
```rust
let Decryptor {
    ciphertext,
    nonce,
    config,
    context
} = decryptor;
```

Then you can directly access e.g. `ciphertext` and manually convert each field to bytes using the `into` / `try_into` / `to_vec` fields.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +        let nonce: Vec<u8> = decryptor.nonce.to_vec();
Also, the nonce doesn't need to be converted `to_vec`. You should be able to use the generic array in the same way as the vecs.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +        }
note: I think you don't need this check; `take_bytes` will fail if it doesn't get exactly `context_length` bytes. In other places, we use a manual length check when we use the `ParseBytes::take_rest` method, which doesn't take a length as parameter.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +        }
suggestion: This reads as kind of confusing to me. I would probably hardcode the nonce length (since we've already hardcoded the chacha parameters everywhere by dint of using `chacha20poly1305` explicitly) like:
```rust
let nonce_length = parse.take_bytes_as_u16()?;
let nonce: [u8; 12] = parse.take_bytes(nonce_length as usize)?.try_into()
            .map_err(|_| CryptoError::ConversionError)?;
```
Then just do `nonce.into()` when you create `self` down at the bottom to turn it back to a generic array.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +        }
todo: Again, don't need this length check because it is handled by `take_bytes`.

2023-08-16 19:29 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +    fn decryptor_vec_u8_conversion() -> Result<(), CryptoError> {
suggestion: This is a good happy test. You might consider adding sad tests that break each field / length to ensure that we need every field to be encoded, and that all the lengths need to be correct. Will leave that up to you.

2023-08-25 18:54 UTC, tposavec commented
> Thanks! I have a few comments about ways to simplify and reduce cloning throughout.
> 
> Are the changes to the `Password` type supposed to be here? They don't seem related to the issue description.

@marsella sorry, it seemed like a minor change, but you are correct it is not related to the issue description.  Would you prefer I submit a separate PR for the password related change?

2023-08-25 19:14 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +        let nonce: Vec<u8> = decryptor.nonce.to_vec();
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/ccb79975ea7c41b72783ba8a7cb843a489a183f5

2023-08-25 19:18 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +        }
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/c5c8e52ce54e3e06ca1d365bb8b9044021ecd77b

2023-08-25 19:32 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +        }
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/42864625aec4d500f839738867f411a4d821dc04

2023-08-25 19:35 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +        }
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/commit/42864625aec4d500f839738867f411a4d821dc04

2023-08-25 20:56 UTC, tposavec commented on lock-keeper-client/src/client.rs
> +        Password(bytes.to_vec())
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/a3bdbfcae7265409e67f9c432f9981bb3bd7e609

2023-08-25 22:40 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +    fn decryptor_vec_u8_conversion() -> Result<(), CryptoError> {
@marsella fixed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/589373dc99e5b0980d41a0a27a7909ba575c97fc

2023-08-28 20:22 UTC, marsella approved these changes
We discussed the `Password` change offline; it's fine to wrap into this PR. I mainly wanted to make sure it was intentional, and to flag that type for further review to make sure it's as misuse-resistant as possible for the uses cases we need it for.

This looks good, otherwise. I raised one concern about memory management but I would say it's non-blocking; if Omar shares my concern then we should probably make a separate issue and review all the `From<Vec<u8>>` instances in this repo to make sure we're zeroizing appropriately.

The other comments are suggestions.

2023-08-28 20:22 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +    fn decryptor_conversion_test_incomplete_fields() -> Result<(), CryptoError> {
This is an absolute aesthetic nit.

I like to name tests to describe the invariant or property that they're testing. Especially with Rust where `cargo test` spits out all the names onto the terminal, it can be helpful to get little descriptive sentences rather than sort of keyword collections.

So, for the three tests you have here, I would name them something like:
- ` decryptor_from_bytes_requires_all_fields`
- `decryptor_from_bytes_cannot_have_extra_bytes`
- `decryptor_vec_u8_conversion_works`

2023-08-28 21:39 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +            .map_err(|_| CryptoError::ConversionError)?;
Addressed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/773fd51af64fd24fd73a24c698830143d64dbb64

2023-08-28 21:54 UTC, tposavec commented on lock-keeper/src/crypto/cryptor.rs
> +    fn decryptor_conversion_test_incomplete_fields() -> Result<(), CryptoError> {
Changed here https://github.com/boltlabs-inc/key-mgmt/pull/550/commits/1421e5494357eb9f4a5f59d32d39ec73f7025a5a

2023-08-29 19:33 UTC, gatoWololo commented on lock-keeper/src/crypto/cryptor.rs
> +impl TryFrom<Vec<u8>> for Decryptor {
> I can't tell from here whether the try_intos zeroize at the end

Good question! `.try_into` is a generic implementation for anything that implements `TryFrom`. From the standard library:
```rust
// TryFrom implies TryInto
#[stable(feature = "try_from", since = "1.34.0")]
impl<T, U> TryInto<U> for T
where
    U: TryFrom<T>,
{
    type Error = U::Error;

    #[inline]
    fn try_into(self) -> Result<U, U::Error> {
        U::try_from(self)
    }
}
```
So as long as our `TryFrom` instances are correctly zeroizing the bytes, then we are good.

> I'm not sure if Rust memory management semantics will copy the bytes as they get passed to try_into so there's another extra copy around

Out of the 3 conversion:
```rust
Ok(Self {
            ciphertext,
            context: context.try_into()?,
            nonce: nonce.try_into()?,
            config: config.try_into()?,
        })
```
Both `context` and `config` are `Vec<u8>` so no copying is happening when calling `.try_into`. The vectors are being passed "by value". `nonce` is `[u8; 12]`, this is probably being copied onto the stack when passed into `.try_into`. I'm not sure if there is much we can do about this, as the value is technically _moved_ by the call, so we cannot zeroize it.

2023-08-29 19:53 UTC, marsella commented on lock-keeper/src/crypto/cryptor.rs
> +impl TryFrom<Vec<u8>> for Decryptor {
Okay, thanks. Then yeah, let's just leave this as is for now.

2023-08-29 22:07 UTC, merged