Opaque authenticate
boltlabs-inc/key-mgmt pull request #58
Opened 2022-07-06 09:52 UTC by gijsvl

To review this opaque authentication I've created a PR into `opaque-register`, once that branch has been merged, we will change this PR to merge with `main` branch. But in this way the PR can already be reviewed

2022-07-07 21:57 UTC, marsella requested changes
Thanks for taking this on -- I appreciate the work you put in to figure out the opaque library and start integrating it into the APIs.

My primary issues here are similar to those in #55:
- I think we should stop using/expanding the client CLI. I think it will improve code quality to have a simpler, more appropriate interface for calling client functions.
- There's a lot of `unwrap`s around this PR. I think it's important to set the foundation for non-panicking error handling from the beginning, even in pieces of code that we don't intend to use for the long run. I commented some of them, but I don't want to approve this until all the unwraps are either gone or have documentation explaining why they won't panic.
- The testing in this repo is evolving into two dueling systems with unclear (to me) distinctions. I think we should converge on one -- probably the custom test harness.

There are also a few tests I would have expected to see here that didn't appear, like
- registering with the same user twice fails
- a registered user can open multiple sessions
- opening a session with an unregistered user id fails

I recognize that this codebase comes with some technical baggage that we imported from zeekoe. I'm hoping to reduce this as much as possible in the early stages of this project. I've made a couple comments to that effect, pointing out places that I think are historical artifacts that no longer serve us.

Apologies for some duplicated comments within this PR and across this and #55.

2022-07-07 21:57 UTC, marsella commented on tests/local_client.rs
> +}
question: It looks like the point of this is to bundle multiple tests together under the same server setup and teardown. This raises the same questions I had in #55 about what the different goals are for this test suite vs the `main+common` test suite. The point of that suite is to do exactly this -- make common setup and teardown functions for all of our tests.

2022-07-07 21:57 UTC, marsella commented on src/local_client.rs
> +    pub session_key: [u8; 64],
todo: Make this a private field, then add a constructor and a public accessor method.

2022-07-07 21:57 UTC, marsella commented on src/cli/client.rs
> +}
todo: I have the same feedback as in #55:
- Replace these `Strings` with the actual types we want to use (`UserId`, `Password`).
- Rename `username` to `user_id` -- we don't have plans to add a meaningful / human-readable username.
- Consider deprecating the CLI and just defining an `authenticate` function that takes these as parameters.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/client.rs
> +    pub username: String,
todo: replace with `user_id: UserId`.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +pub struct Authenticate;
suggestion: I think this structure is an artifact of a non-ideal design decision in zeekoe that assumed all commands coming into the server would have the same set of parameters, so we defined a `Command` trait and these unit structs to implement their corresponding `run` functions.

In fact, that wasn't a helpful structure and I think we dropped the trait (in any case, it doesn't appear here). Maybe @leboiko can weigh in on whether it's better to have a unit struct with a `run` function vs just having an unattached `authenticate` or `run_authenticate` function?

In either case, the `run` function here takes a bunch of ignored parameters that I would prefer to delete. Is there a benefit to keeping them around?

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +        let password_file_serialized = retrieve_opaque(service, auth_start.username.clone());
suggestion: when you replace `username: String` with `user_id: UserId`, you should be able to drop this `clone` because user ids are `Copy` (if not, you should make them `Copy`).

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +        let password_file = ServerRegistration::<OpaqueCipherSuite>::deserialize(
nitpick: Can we rename this to something about `authentication` or `opaque` or `client_auth` instead of `password`? I don't want to confuse future developers.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +        .unwrap();
todo: please remove the `unwrap`s throughout.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +        let mut rng = OsRng;
question: Is there a reason you can't use the `StdRng` passed in as a parameter? I would prefer to keep our rng behavior a bit more centralized.

2022-07-07 21:57 UTC, marsella commented on src/local_client.rs
> +            username: user_id.0.clone(),
suggestion: I think it is also fine to pass the `UserId` by reference. 

This comes back to my other comment -- I don't think it makes sense to retcon a CLI tool to call a function. I'd rather see just a plain `register` function that also takes a `user_id` by reference so we don't have to clone all this stuff here (we're not creating anything that will persist outside of this function, so it doesn't make sense that we'd have to be cloning these objects).

2022-07-07 21:57 UTC, marsella commented on tests/main.rs
> +    Authenticate,
todo: I noted this in #55, too, but I think this should take a username and password instead of hard-coding them.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/client/authenticate.rs
> +        let mut rng = OsRng;
todo: I don't think `OsRng` is the best choice here, and I don't like distributing the RNG choice to each client operation. Our randomness best practices recommend `StdRng` or `ThreadRng`. Perhaps you can make an `rng` function in the main module file (`client.rs`) that returns one of the recommended versions with the type `impl CryptoRng + RngCore`and call it from each function that needs a RNG. That way we have the flexibility to switch it out across the whole client more easily.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/client/authenticate.rs
> +        // ...and select the Create session
todo: replace this comment and the context with `authenticate session`, not create.

2022-07-07 21:57 UTC, marsella commented on src/key_mgmt/client/authenticate.rs
> +            ClientLogin::<OpaqueCipherSuite>::start(&mut rng, password.as_bytes()).unwrap();
todo: remove this unwrap.

2022-07-07 21:57 UTC, marsella commented on tests/main.rs
> +            operations: vec![(Operation::Authenticate, Outcome { error: None })],
todo: I expect this test to fail without a registration step first. I'm guessing it doesn't because the `test_user` username is hard-coded across every register and authenticate step. Can you update this test to throw an error and make another passing test that registers and authenticates?

2022-07-13 16:51 UTC, marsella reviewed
Thanks for making those changes, this is looking much better!

There are two main cryptography issues I see here:
1. We're using a version of the opaque library that has been yanked / unpublished from the crate index. I think we should stop using this.
2. The random number generator selection behavior is not very centralized right now - we just create one whenever we need one. This doesn't adhere to our RNG standards and I think we should try as much as possible to make RNGs mutable parameters that are passed around to functions.

There are also a bunch of Rust idiom comments. @vidyaap has agreed to take on most of these and I've tried to tag her in the relevant comments, but it might be instructive for @gijsvl to read through those to see what to do in the future.

2022-07-13 16:51 UTC, marsella commented on src/local_client.rs
> +        let client_registration_start_result = match ClientRegistration::<OpaqueCipherSuite>::start(
todo: Replace `match` with a `map_err`.

2022-07-13 16:51 UTC, marsella commented on src/local_client.rs
> +    ) -> Result<(), anyhow::Error> {
todo: Replace the error type with our `SessionError` and replace all the hard-coded `anyhow` errors with new variants in that enum. @vidyaap

2022-07-13 16:51 UTC, marsella commented on src/local_client.rs
> +        let client_finish_registration_result = match client_registration_start_result.state.finish(
todo: Replace `match` with `map_err`. @vidyaap

2022-07-13 16:51 UTC, marsella commented on src/opaque_storage.rs
> +    match server_key_file {
todo: Can you add short inline comments describing which branch is "create new" and which is "retrieve existing"? @vidyaap

2022-07-13 16:51 UTC, marsella commented on tests/main.rs
> +                        .map_err(|e| anyhow!(e.to_string()))
todo: Can we replace the `anyhow!` with a plain `into`? I think the `thiserror::Error` trait automatically implements that conversion. If so, there's another instance down on L228. @vidyaap

2022-07-13 16:51 UTC, marsella commented on tests/main.rs
> +                    let client_config = client::Config::load(common::CLIENT_CONFIG)
todo: Use the client config passed in as a parameter. @vidyaap

2022-07-13 16:51 UTC, marsella commented on tests/main.rs
> +                    let client_config = client::Config::load(common::CLIENT_CONFIG)
todo: use the client config passed in as a parameter. @vidyaap

2022-07-13 17:12 UTC, indomitableSwan commented on Cargo.toml
>  [dependencies]
I'd prefer to use the most recent unstable version for now. We want to be using a library that matches the current version of the RFC and may even want to be helping to improve the library, as capacity allows. For deployment, the only alternative I can think of (besides switching to a different aPAKE entirely) is to write our own implementation of OPAQUE that tracks the most recent changes, which seems like a much heavier lift.

There are a quite a few changes in the RFC since the one captured in 1.2.0, most of which we care about.

2022-07-15 08:13 UTC, gijsvl commented on src/key_mgmt/server/authenticate.rs
> +        };
I don't believe `map_err` achieves what we want here, because it returns a new result, while in this case we either want the unwrapped object or send an abort... Unless I'm missing something

2022-07-15 12:01 UTC, marsella commented on src/key_mgmt/server/authenticate.rs
> +        };
Oh, good catch.

2022-07-15 14:59 UTC, marsella commented on src/local_client.rs
> +        let mut rng = OsRng;
Update: Gijs replaced the `OsRng` with a `StdRng` parameter, but I think it's still a good option to use the `impl CryptoRng` type to describe the behavior we want, rather than restricting ourselves to the specific `StdRng`.

2022-07-15 15:04 UTC, marsella commented on tests/main.rs
> +                    let client_config = client::Config::load(common::CLIENT_CONFIG)
I wasn't clear about this. The execute function takes a `client_config` as a parameter, so we can use that one instead of making it anew here. @vidyaap, can you revert the change that adds a client config as a parameter to the `Operation` enum variants?

2022-07-15 16:20 UTC, vidyaap commented on src/local_client.rs
> +    ) -> Result<(), anyhow::Error> {
I'm not sure what to do with the `context` errors here though. It looks like because they are from `anyhow` errors in the `connect()` function, that the return type still needs to be the `anyhow` one.

2022-07-15 16:21 UTC, vidyaap commented on src/local_client.rs
> +    ) -> Result<(), anyhow::Error> {
I could probably leave the return type on this and the next comment, but still change the hard-coded `anyhow`s to `SessionErrors` though

2022-07-15 17:51 UTC, vidyaap commented on tests/main.rs
> +            operations: vec![(Operation::Authenticate, Outcome { error: None })],
I think the trade-off is having to hard code unique strings into the tests vs. having to go into the DB to delete things. As long as each test is an isolated set of events, which both of these options allow, then it’s up to us what we prefer. Maybe we can leave it as is until we implement the first pass of the DB and see how complicated switching it would be then?

2022-07-15 18:11 UTC, marsella commented on tests/main.rs
> +            operations: vec![(Operation::Authenticate, Outcome { error: None })],
That sounds like a good plan to me.

2022-07-15 19:51 UTC, vidyaap commented on tests/main.rs
> +                        expected_error: Some(anyhow!("RegistrationFailed")),
Probably, we can make an enum in the tests to wrap around our custom errors (including `SessionError` in this case) so we can use that enum as the parameter of the `Outcome` type. Made #86 as a placeholder issue for this, but it will need fleshing out.

2022-07-15 19:53 UTC, vidyaap commented on src/local_client.rs
> +    ) -> Result<(), anyhow::Error> {
Left the return types, but changed as many `context`s and hard-coded `anyhow`s as I could. The `offer_abort!` macro is the only thing left that makes us return anyhow errors here, so I made #85 to handle that later.

2022-07-15 20:06 UTC, marsella commented on src/local_client.rs
> +    ) -> Result<(), anyhow::Error> {
Thanks, I forgot about all the `context`s!

2022-07-15 21:21 UTC, marsella commented on src/protocol.rs
> +        3 => Authenticate,
Added #87 to capture this.

2022-07-18 22:44 UTC, marsella approved these changes
Thanks @vidyaap and @gijsvl for addressing all these comments! Looks much improved.

2022-07-18 22:44 UTC, merged