WIP add functionality to seal a signing private key
boltlabs-inc/key-mgmt pull request #630
Opened 2024-02-05 21:35 UTC by krs85

This PR implements #627.

2024-02-14 21:08 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn seal_attestation_private_key(
The original function was `new()` (a constructor) that was called from a wrapper function called `seal_attestation_key()`. This function does more than construct an `EncryptedAttestationPrivateKey`, but I also found it confusing to call its constructor from another function. So I removed `seal_attestation_key()` and renamed this function.

2024-02-14 21:12 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +use aes_gcm_siv::{
I wasn't totally sure _where_ to put `EncrpytedAttestationPrivateKey` and `UnsealedAttestationKey`. After going through the lock keeper code, I couldn't find an existing file that felt like the right place, but I do still feel that they belong under `crypto`. Making this comment because I am open to suggestions if anyone thinks there's a better spot for them!

2024-02-15 15:12 UTC, krs85 commented on lock-keeper/Cargo.toml
> +aes-gcm-siv = "0.11"                                                # Used for encryption/decryption of sharded keys.
I don't know why my IDE keeps formatting this this way. 🥲

2024-02-15 15:17 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +}
I removed the original `serialize()` and `deserialize()` methods for `EncryptedAttestationPrivateKey`, because they were just wrappers around `bincode::serialize()` and `bincode::deserialize()`.

2024-02-15 15:51 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
I _could_  make the `nonce` a public field, but the other field isn't public, and it just doesn't seem worth it to me.

2024-02-15 15:52 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +impl EncryptedAttestationPrivateKey {
I removed the original `serialize()` and `deserialize()` methods for `EncryptedAttestationPrivateKey` because they were just wrappers around `bincode::serialize()` and `bincode::deserialize()`.

2024-02-21 18:38 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    nonce: GenericArray<u8, U12>,
We should use the type `Nonce` here, it can be imported as: `use aes_gcm_siv::Nonce`.

2024-02-21 18:42 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn seal_attestation_private_key(
I like this change could we rename this function to just `seal` since it is an associated function we have to call it as `EncryptedAttestationPrivateKey::seal(...)`. I think this cuts down on some verbosity.

2024-02-21 18:44 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +        let attestation_private_key_sealed = cipher
Minor nit: rename `attestation_private_key_sealed` to just `sealed` or `encrypted`.

2024-02-21 18:44 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +        let nonce: GenericArray<u8, U12> = GenericArray::clone_from_slice(&self.nonce);
Use `Nonce` type here instead of `GenericArray`

2024-02-21 18:45 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn into_string(self) -> Result<String, CryptoError> {
Add newline here.

2024-02-21 18:45 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn from_string(attestation_key_string: String) -> Result<Self, CryptoError> {
Add newline here.

2024-02-21 18:46 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn set_nonce(&mut self, new_nonce: Nonce) {
Why is this needed? Does the caller need to be able to change the `Nonce` of an already constructed `Self`?

2024-02-21 18:46 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
Why is this fn needed? Does the caller need to be able to change the `Nonce` of an already constructed `Self`?

2024-02-21 18:48 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn into_string(self) -> Result<String, CryptoError> {
Would a better name for this be `into_base64`?

2024-02-21 18:48 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn from_string(attestation_key_string: String) -> Result<Self, CryptoError> {
And this could be `from_base64`?

2024-02-21 18:51 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn decrypt(self, seal_key: &SealKey) -> Result<SigningPrivateKey, CryptoError> {
We actually don't need the Nonce cloning here:
```rust
let cipher = Aes256GcmSiv::new(seal_key.as_ref());
        let decrypted = cipher
            .decrypt(&self.nonce, self.encrypted.as_slice())
            .map_err(|_err| CryptoError::DecryptionFailed)?;
```
This works :)

2024-02-21 18:51 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +        SigningPrivateKey::from_bytes(&decrypted).map_err(|_err| CryptoError::ConversionError)
Should we call `zeroize` on `decrypted` here? I think so.

2024-02-21 20:14 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +pub struct UnsealedAttestationKey {
I will make a follow-up issue to refactor change this type. Based on its usage, it does not seem necessary.

2024-02-21 20:14 UTC, gatoWololo requested changes
Looks good! Just some feedback to polish it.

2024-02-21 22:50 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +use aes_gcm_siv::{
This place seems good to me.

2024-02-21 22:50 UTC, gatoWololo commented on lock-keeper/Cargo.toml
> +aes-gcm-siv = "0.11"                                                # Used for encryption/decryption of sharded keys.
lol

2024-02-22 15:15 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn seal_attestation_private_key(
I love that!

2024-02-22 19:18 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +}
Just throwing a comment on this because I want to add documentation / comments to everything in this file, and I need a reminder. Just waiting until we finalize some things!

2024-02-22 21:00 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +        SigningPrivateKey::from_bytes(&decrypted).map_err(|_err| CryptoError::ConversionError)
I *think* I did this right but please check my work 😬

2024-02-22 21:03 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
Yes, in one spot the caller needs to change the `Nonce` of an existing `Self`. It is only in one place, so I don't know if the function is worth it. On the other hand, neither field in `EncryptedAttestationPrivateKey` is `pub` right now, and I don't know if it's good practice to have one of them `pub` and one not.

2024-02-22 21:09 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +pub struct UnsealedAttestationKey {
I decided to just do the fix because it wasn't too complicated. 😅 Let me know what you think.

2024-02-22 21:54 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +        SigningPrivateKey::from_bytes(&decrypted).map_err(|_err| CryptoError::ConversionError)
Yep!

2024-02-22 21:55 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
Okay, I think this is fine then.

2024-02-22 21:59 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
The only usage I found seems to be for a unit test, would it work if we added a `#[cfg(test)]` to this function? IDK if cfg(test) works across dependencies like this.

2024-02-22 22:04 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +pub struct UnsealedAttestationKey {
Can we just get rid of this function all together? This function is just combining two steps:
1) Turn the `sealed_attestation_private_key: &str` into a EncryptedAttestationPrivateKey.
2) And calling `decrypt` on the `EncryptedAttestationPrivateKey`.

Couldn't the calling application just do these two steps in order?

2024-02-22 22:05 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    pub fn from_base64(attestation_key_string: String) -> Result<Self, CryptoError> {
This does not need to be of type `String`. `&str` is sufficient.

2024-02-22 22:05 UTC, gatoWololo requested changes
Looks pretty good. Some final feedback.

2024-02-23 18:24 UTC, krs85 commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +pub struct UnsealedAttestationKey {
The use cases in the application also almost never need both of these at once so... I have no idea what the original reasoning for this type and function were 🤷‍♀️

2024-02-23 19:28 UTC, gatoWololo commented on lock-keeper/src/crypto/seal_signing_private_key.rs
> +    }
Actually, I'm pretty sure my suggestion won't work. good enough IMO

2024-02-27 19:42 UTC, merged