Basic client server #3
boltlabs-inc/key-mgmt pull request #7
Opened 2022-04-08 15:45 UTC by gijsvl

2022-04-25 16:51 UTC, marsella requested changes
Thanks for this PR! Nice to see a bunch of infrastructure in one place. I have some suggestions for simplifying this implementation, since it is currently less complicated than zeekoe and we're not sure exactly how it will add complications. I also have some questions about design decisions, all inline.

2022-04-25 16:51 UTC, marsella commented on src/keymgmt/server.rs
> +                        let rng = StdRng::from_entropy();
Issue: I think this will create a new RNG every time the server gets a request. Is there a way to declare this outside of this function and pass a mutable reference or something instead? I am not sure how the ownership rules will work since this is a `move` block, but I am a bit concerned about repeated instantiation here.

2022-04-25 16:51 UTC, marsella commented on src/lib.rs
> +// #![warn(missing_docs)]
todo: If we're not using this tag, can you delete it?

2022-04-25 16:51 UTC, marsella commented on src/protocol.rs
> +impl Display for Party {
suggestion: Since the display names are the same as the enum variants, you can probably use this shorthand: https://stackoverflow.com/questions/32710187/how-do-i-get-an-enum-as-a-string#32712140

2022-04-25 16:51 UTC, marsella commented on src/protocol.rs
> +    /// ```
Nice doctest!

2022-04-25 16:51 UTC, marsella commented on src/protocol.rs
> +pub mod daemon {
Issue: I don't think we need the daemon protocol yet. Let's remove it until it's necessary.

2022-04-25 16:51 UTC, marsella commented on src/config/client.rs
> +    pub daemon_port: u16,
todo: Please remove daemon, I don't think we need it yet.

2022-04-25 16:51 UTC, marsella commented on src/defaults.rs
> +    }
todo: Please remove daemon, I don't think we need it yet. Even though it's a cute port #.

2022-04-25 16:51 UTC, marsella commented on src/cli/server.rs
> +    Placeholder(Placeholder),
question: Is this so you can have the exhaustive "not implemented" case in the tests? I wouldn't mind deleting that case for now, since you _have_ implemented the tests for everything that exists to be tested. If we add new options here and don't put them in the test, we'll get a compile error and can add a default (or more tests) at that point.

2022-04-25 16:51 UTC, marsella commented on src/keymgmt/server.rs
> +    type Output;
suggestion: You could remove this type entirely for now and simplify the `run` function to return `Result<(), anyhow::Error>`. I'm not sure yet what other server operations we'll have. Since this will behave as more of an actual server than zkchannels, where the merchant server could also initiate protocol executions, we might not need any non-`()` return types.

2022-04-25 16:51 UTC, marsella commented on tests/common.rs
> +enum ServerServices {
suggestion: I over-engineered this in zeekoe because I thought we might want to test multiple server services (e.g. localhosts, other IP addresses, who knows?!), but it turns out we only use the IPv4 version. If you want, you can probably remove all of the `ServerServices` stuff and just make a `const` to hold the server address.

2022-04-29 11:52 UTC, gijsvl commented on src/keymgmt/client/retrieve.rs
> +    type Output = ();
Good point, this was something I wanted to talk to you about. It breaks the e2e tests as they are written now. This is also an issue in zeekoe, but up until now we haven't had any command that also is an action in the e2e test. I was hoping Vidya would solve it in one of the tests she's writing for zeekoe 😅. Let's discuss.

2022-04-29 11:57 UTC, gijsvl commented on src/bin/client.rs
> +        Retrieve(_run) => Ok(()),
Nope, good catch, totally forgot

2022-04-29 12:00 UTC, gijsvl commented on Cargo.toml
> +allow_explicit_certificate_trust = []
I think the only obvious misuse is using the `--all-features` I guess, but I'm not sure we have to optimize for that case. I think the feature already makes it very clear what someone is doing, and I believe we shouldn't worry too much about the edge case. It's gonna give us more headaches than actually preventing anything.

2022-04-29 15:15 UTC, marsella approved these changes
Looks great, thanks for fixing!

2022-05-03 20:22 UTC, marsella commented on src/keymgmt/server.rs
> +                        let rng = StdRng::from_entropy();
Added #20

2022-05-03 20:22 UTC, merged